# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details

from __future__ import annotations

from datetime import datetime

from pydantic import BaseModel, ConfigDict, Field


class WorkflowDetails(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str = Field(..., title="Workflow Name")
    description: str | None = Field("", title="Workflow Description")


class TimezoneInfo(BaseModel):
    label: str = Field(..., title="Label")
    tzCode: str = Field(..., title="Tzcode")
    name: str = Field(..., title="Name")
    utc: str = Field(..., title="Utc")


class EarthRangerConnection(BaseModel):
    name: str = Field(..., title="Data Source")


class ScreenshotConfig(BaseModel):
    width: int | None = Field(1280, title="Width")
    height: int | None = Field(720, title="Height")
    full_page: bool | None = Field(True, title="Full Page")
    device_scale_factor: float | None = Field(2.0, title="Device Scale Factor")
    wait_for_timeout: int | None = Field(
        30000,
        description="Forced wait time (ms) after network idle before taking the screenshot.",
        title="Wait For Timeout",
    )
    timeout: int | None = Field(
        0,
        description="Playwright navigation/screenshot timeout in ms. 0 disables timeouts.",
        title="Timeout",
    )
    max_concurrent_pages: int | None = Field(
        5,
        description="Maximum number of pages open at once when batching.",
        title="Max Concurrent Pages",
    )


class TimeRange(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    since: datetime = Field(..., description="The start time", title="Since")
    until: datetime = Field(..., description="The end time", title="Until")
    timezone: TimezoneInfo | None = Field(None, title="Timezone")
    time_format: str | None = Field(
        "%d %b %Y %H:%M:%S", description="The time format", title="Time Format"
    )


class ErClientName(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data_source: EarthRangerConnection = Field(
        ..., description="Select one of your configured data sources.", title=""
    )


class ConvertChartHtmlPng(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    config: ScreenshotConfig | None = Field(
        default_factory=lambda: ScreenshotConfig.model_validate(
            {
                "width": 1280,
                "height": 720,
                "full_page": True,
                "device_scale_factor": 2.0,
                "wait_for_timeout": 30000,
                "timeout": 0,
                "max_concurrent_pages": 5,
            }
        ),
        description="The screenshot configuration",
        title="Config",
    )


class FormData(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    workflow_details: WorkflowDetails | None = Field(
        None,
        description="Add information that will help to differentiate this workflow from another.",
        title="Set workflow details",
    )
    time_range: TimeRange | None = Field(
        None, description="Choose the period of time to analyze.", title="Time range"
    )
    er_client_name: ErClientName | None = Field(None, title="Connect to ER")
    convert_chart_html_png: ConvertChartHtmlPng | None = Field(
        None, title="Convert chart htmls to png"
    )
