# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import List, Literal, Optional, Union

from pydantic import BaseModel, ConfigDict, Field, confloat, constr


class WorkflowDetails(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str = Field(..., title="Workflow Name")
    description: Optional[str] = Field("", title="Workflow Description")


class Url(str, Enum):
    https___tile_openstreetmap_org__z___x___y__png = (
        "https://tile.openstreetmap.org/{z}/{x}/{y}.png"
    )


class BaseMaps(BaseModel):
    url: Literal["https://tile.openstreetmap.org/{z}/{x}/{y}.png"] = Field(
        "https://tile.openstreetmap.org/{z}/{x}/{y}.png", title="Preset Layer URL"
    )
    opacity: Optional[confloat(ge=0.0, le=1.0)] = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class Url1(str, Enum):
    https___server_arcgisonline_com_ArcGIS_rest_services_World_Street_Map_MapServer_tile__z___y___x_ = "https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}"


class BaseMaps1(BaseModel):
    url: Literal[
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}"
    ] = Field(
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}",
        title="Preset Layer URL",
    )
    opacity: Optional[confloat(ge=0.0, le=1.0)] = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class Url2(str, Enum):
    https___server_arcgisonline_com_ArcGIS_rest_services_World_Imagery_MapServer_tile__z___y___x_ = "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}"


class BaseMaps2(BaseModel):
    url: Literal[
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}"
    ] = Field(
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",
        title="Preset Layer URL",
    )
    opacity: Optional[confloat(ge=0.0, le=1.0)] = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class Url3(str, Enum):
    https___server_arcgisonline_com_ArcGIS_rest_services_World_Topo_Map_MapServer_tile__z___y___x_ = "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}"


class BaseMaps3(BaseModel):
    url: Literal[
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}"
    ] = Field(
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}",
        title="Preset Layer URL",
    )
    opacity: Optional[confloat(ge=0.0, le=1.0)] = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class Url4(str, Enum):
    https___tiles_arcgis_com_tiles_POUcpLYXNckpLjnY_arcgis_rest_services_landDx_basemap_tiles_mapservice_MapServer_tile__z___y___x_ = "https://tiles.arcgis.com/tiles/POUcpLYXNckpLjnY/arcgis/rest/services/landDx_basemap_tiles_mapservice/MapServer/tile/{z}/{y}/{x}"


class BaseMaps4(BaseModel):
    url: Literal[
        "https://tiles.arcgis.com/tiles/POUcpLYXNckpLjnY/arcgis/rest/services/landDx_basemap_tiles_mapservice/MapServer/tile/{z}/{y}/{x}"
    ] = Field(
        "https://tiles.arcgis.com/tiles/POUcpLYXNckpLjnY/arcgis/rest/services/landDx_basemap_tiles_mapservice/MapServer/tile/{z}/{y}/{x}",
        title="Preset Layer URL",
    )
    opacity: Optional[confloat(ge=0.0, le=1.0)] = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class Url5(str, Enum):
    https___server_arcgisonline_com_arcgis_rest_services_Elevation_World_Hillshade_MapServer_tile__z___y___x_ = "https://server.arcgisonline.com/arcgis/rest/services/Elevation/World_Hillshade/MapServer/tile/{z}/{y}/{x}"


class BaseMaps5(BaseModel):
    url: Literal[
        "https://server.arcgisonline.com/arcgis/rest/services/Elevation/World_Hillshade/MapServer/tile/{z}/{y}/{x}"
    ] = Field(
        "https://server.arcgisonline.com/arcgis/rest/services/Elevation/World_Hillshade/MapServer/tile/{z}/{y}/{x}",
        title="Preset Layer URL",
    )
    opacity: Optional[confloat(ge=0.0, le=1.0)] = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class BaseMaps6(BaseModel):
    url: Optional[
        constr(
            pattern=r"https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}([-a-zA-Z0-9()@:%_\+.~#?&//=\{\}]*)"
        )
    ] = Field(
        "https://example.tiles.com/{z}/{x}/{y}.png",
        description="The URL of a publicly accessible tiled raster service.",
        title="Custom Layer URL",
    )
    opacity: Optional[confloat(ge=0.0, le=1.0)] = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Custom Layer Opacity",
    )
    max_zoom: Optional[int] = Field(
        20,
        description="Set the maximum zoom level to fetch tiles for.",
        title="Custom Layer Max Zoom",
    )
    min_zoom: Optional[int] = Field(
        0,
        description="Set the minimum zoom level to fetch tiles for.",
        title="Custom Layer Min Zoom",
    )


class ConfigureBaseMaps(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    base_maps: Optional[
        List[
            Union[
                BaseMaps,
                BaseMaps1,
                BaseMaps2,
                BaseMaps3,
                BaseMaps4,
                BaseMaps5,
                BaseMaps6,
            ]
        ]
    ] = Field(
        [
            {
                "url": "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}",
                "opacity": 1,
                "max_zoom": 20,
            },
            {
                "url": "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",
                "opacity": 0.5,
                "max_zoom": 20,
            },
        ],
        description="Select tile layers to use as base layers in map outputs. The first layer in the list will be the bottommost layer displayed.",
        title=" ",
    )


class OverallGrazingZones(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    reset_index: Optional[bool] = Field(
        False, description="If reset index, default is False", title="Reset Index"
    )


class SubjectObservations(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    subject_group_name: str = Field(..., title="Subject Group Name")


class DfWithTemporalIndex(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    cast_to_datetime: Optional[bool] = Field(
        True,
        description="Whether to attempt casting `time_col` to datetime.",
        title="Cast To Datetime",
    )
    format: Optional[str] = Field(
        "mixed",
        description='            If `cast_to_datetime=True`, the format to pass to `pd.to_datetime`\n            when attempting to cast `time_col` to datetime. Defaults to "mixed".\n            ',
        title="Format",
    )


class EventsWtemporal(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    cast_to_datetime: Optional[bool] = Field(
        True,
        description="Whether to attempt casting `time_col` to datetime.",
        title="Cast To Datetime",
    )
    format: Optional[str] = Field(
        "mixed",
        description='            If `cast_to_datetime=True`, the format to pass to `pd.to_datetime`\n            when attempting to cast `time_col` to datetime. Defaults to "mixed".\n            ',
        title="Format",
    )


class FilterPatrolInfoEvents(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    reset_index: Optional[bool] = Field(
        False, description="If reset index, default is False", title="Reset Index"
    )


class StatusEnum(str, Enum):
    active = "active"
    overdue = "overdue"
    done = "done"
    cancelled = "cancelled"


class ErPatrolAndEventsParams(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    status: Optional[List[StatusEnum]] = Field(
        ["done"],
        description="Choose to analyze patrols with a certain status. If left empty, patrols of all status will be analyzed",
        title="Patrol Status",
    )
    include_null_geometry: Optional[bool] = Field(
        True, title="Include Events Without a Geometry (point or polygon)"
    )


class FilterFootPatrols(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    reset_index: Optional[bool] = Field(
        False, description="If reset index, default is False", title="Reset Index"
    )


class FilterVehiclePatrols(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    reset_index: Optional[bool] = Field(
        False, description="If reset index, default is False", title="Reset Index"
    )


class FilterMotorPatrols(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    reset_index: Optional[bool] = Field(
        False, description="If reset index, default is False", title="Reset Index"
    )


class FilterMobileBoma(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    reset_index: Optional[bool] = Field(
        False, description="If reset index, default is False", title="Reset Index"
    )


class FilterPredation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    reset_index: Optional[bool] = Field(
        False, description="If reset index, default is False", title="Reset Index"
    )


class ReplaceSpeciesNull(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    column_name: str = Field(..., title="Column Name")


class TimezoneInfo(BaseModel):
    label: str = Field(..., title="Label")
    tzCode: str = Field(..., title="Tzcode")
    name: str = Field(..., title="Name")
    utc: str = Field(..., title="Utc")


class EarthRangerConnection(BaseModel):
    name: str = Field(..., title="Data Source")


class TrajectorySegmentFilter(BaseModel):
    min_length_meters: Optional[confloat(ge=0.001)] = Field(
        0.001, title="Minimum Segment Length (Meters)"
    )
    max_length_meters: Optional[confloat(gt=0.001)] = Field(
        100000, title="Maximum Segment Length (Meters)"
    )
    min_time_secs: Optional[confloat(ge=1.0)] = Field(
        1, title="Minimum Segment Duration (Seconds)"
    )
    max_time_secs: Optional[confloat(gt=1.0)] = Field(
        172800, title="Maximum Segment Duration (Seconds)"
    )
    min_speed_kmhr: Optional[confloat(gt=0.001)] = Field(
        0.01, title="Minimum Segment Speed (Kilometers per Hour)"
    )
    max_speed_kmhr: Optional[confloat(gt=0.001)] = Field(
        500, title="Maximum Segment Speed (Kilometers per Hour)"
    )


class TimeRange(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    since: datetime = Field(..., description="The start time", title="Since")
    until: datetime = Field(..., description="The end time", title="Until")
    timezone: Optional[TimezoneInfo] = Field(None, title="Timezone")


class ErClientName(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data_source: EarthRangerConnection = Field(
        ..., description="Select one of your configured data sources.", title=""
    )


class FootTrajs(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    trajectory_segment_filter: Optional[TrajectorySegmentFilter] = Field(
        default_factory=lambda: TrajectorySegmentFilter.model_validate(
            {
                "min_length_meters": 0.001,
                "max_length_meters": 100000,
                "min_time_secs": 1,
                "max_time_secs": 172800,
                "min_speed_kmhr": 0.01,
                "max_speed_kmhr": 500,
            }
        ),
        description="Filter track data by setting limits on track segment length, duration, and speed. Segments outside these bounds are removed, reducing noise and to focus on meaningful movement patterns.",
        title=" ",
    )


class VehicleTrajs(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    trajectory_segment_filter: Optional[TrajectorySegmentFilter] = Field(
        default_factory=lambda: TrajectorySegmentFilter.model_validate(
            {
                "min_length_meters": 0.001,
                "max_length_meters": 100000,
                "min_time_secs": 1,
                "max_time_secs": 172800,
                "min_speed_kmhr": 0.01,
                "max_speed_kmhr": 500,
            }
        ),
        description="Filter track data by setting limits on track segment length, duration, and speed. Segments outside these bounds are removed, reducing noise and to focus on meaningful movement patterns.",
        title=" ",
    )


class MotorTrajs(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    trajectory_segment_filter: Optional[TrajectorySegmentFilter] = Field(
        default_factory=lambda: TrajectorySegmentFilter.model_validate(
            {
                "min_length_meters": 0.001,
                "max_length_meters": 100000,
                "min_time_secs": 1,
                "max_time_secs": 172800,
                "min_speed_kmhr": 0.01,
                "max_speed_kmhr": 500,
            }
        ),
        description="Filter track data by setting limits on track segment length, duration, and speed. Segments outside these bounds are removed, reducing noise and to focus on meaningful movement patterns.",
        title=" ",
    )


class Params(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    workflow_details: Optional[WorkflowDetails] = Field(
        None,
        description="Add information that will help to differentiate this workflow from another.",
        title="Set workflow details",
    )
    time_range: Optional[TimeRange] = Field(
        None, description="Choose the period of time to analyze.", title="Time range"
    )
    er_client_name: Optional[ErClientName] = Field(None, title="Connect to ER")
    configure_base_maps: Optional[ConfigureBaseMaps] = Field(
        None, title="Configure base map layers"
    )
    overall_grazing_zones: Optional[OverallGrazingZones] = Field(
        None, title="Create group ranch gdf from loaded gdf"
    )
    subject_observations: Optional[SubjectObservations] = Field(
        None, title="Get subject observations from ER"
    )
    df_with_temporal_index: Optional[DfWithTemporalIndex] = Field(
        None, title="Add temporal index"
    )
    events_wtemporal: Optional[EventsWtemporal] = Field(
        None, title="Add temporal index on events"
    )
    filter_patrol_info_events: Optional[FilterPatrolInfoEvents] = Field(
        None, title="Filter events and get patrol information records"
    )
    er_patrol_and_events_params: Optional[ErPatrolAndEventsParams] = Field(
        None, title="patrol and event types"
    )
    filter_foot_patrols: Optional[FilterFootPatrols] = Field(
        None, title="Filter foot patrol observations"
    )
    filter_vehicle_patrols: Optional[FilterVehiclePatrols] = Field(
        None, title="Filter vehicle patrol observations"
    )
    filter_motor_patrols: Optional[FilterMotorPatrols] = Field(
        None, title="Filter motorbike patrol observations"
    )
    foot_trajs: Optional[FootTrajs] = Field(
        None, title="Convert foot relocations to trajectories"
    )
    vehicle_trajs: Optional[VehicleTrajs] = Field(
        None, title="Convert vehicle relocations to trajectories"
    )
    motor_trajs: Optional[MotorTrajs] = Field(
        None, title="Convert motorbike relocations to trajectories"
    )
    filter_mobile_boma: Optional[FilterMobileBoma] = Field(
        None, title="Filter events to get mobile boma rep"
    )
    filter_predation: Optional[FilterPredation] = Field(
        None, title="Filter events to get livestock predation events"
    )
    replace_species_null: Optional[ReplaceSpeciesNull] = Field(
        None, title="Replace livestock species null with unknown"
    )
