# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details

# ruff: noqa: E402

"""WARNING: This file is generated in a testing context and should not be used in production.
Lines specific to the testing context are marked with a test tube emoji (🧪) to indicate
that they would not be included (or would be different) in the production version of this file.
"""

import json
import os
import warnings  # 🧪

from ecoscope_workflows_core.tasks.config import set_workflow_details
from ecoscope_workflows_core.tasks.filter import set_time_range
from ecoscope_workflows_core.tasks.groupby import set_groupers
from ecoscope_workflows_core.tasks.io import set_er_connection
from ecoscope_workflows_core.testing import create_task_magicmock  # 🧪
from ecoscope_workflows_ext_custom.tasks.results import set_base_maps_pydeck
from ecoscope_workflows_ext_mnc.tasks import (
    clean_file_keys,
    create_map_layers,
    download_file_and_persist,
    load_geospatial_files,
    make_text_layer,
    select_koi,
)

get_subjectgroup_observations = create_task_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_ecoscope.tasks.io",  # 🧪
    func_name="get_subjectgroup_observations",  # 🧪
)  # 🧪
from ecoscope_workflows_core.tasks.io import persist_text
from ecoscope_workflows_core.tasks.transformation import (
    add_temporal_index,
    extract_column_as_type,
    extract_value_from_json_column,
    map_columns,
)
from ecoscope_workflows_ext_custom.tasks.io import html_to_png
from ecoscope_workflows_ext_ecoscope.tasks.analysis import summarize_df
from ecoscope_workflows_ext_ecoscope.tasks.io import persist_df
from ecoscope_workflows_ext_ecoscope.tasks.results import draw_line_chart

get_events = create_task_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_ecoscope.tasks.io",  # 🧪
    func_name="get_events",  # 🧪
)  # 🧪
from ecoscope_workflows_core.tasks.io import persist_text
from ecoscope_workflows_core.tasks.results import gather_dashboard
from ecoscope_workflows_core.tasks.transformation import (
    add_temporal_index,
    extract_column_as_type,
)
from ecoscope_workflows_ext_ecoscope.tasks.analysis import summarize_df
from ecoscope_workflows_ext_ecoscope.tasks.io import persist_df
from ecoscope_workflows_ext_ecoscope.tasks.results import draw_line_chart
from ecoscope_workflows_ext_mnc.tasks import add_totals_row, filter_by_value

from ..params import Params


def main(params: Params):
    warnings.warn("This test script should not be used in production!")  # 🧪

    params_dict = json.loads(params.model_dump_json(exclude_unset=True))

    workflow_details = (
        set_workflow_details.validate()
        .handle_errors(task_instance_id="workflow_details")
        .partial(**(params_dict.get("workflow_details") or {}))
        .call()
    )

    time_range = (
        set_time_range.validate()
        .handle_errors(task_instance_id="time_range")
        .partial(
            time_format="%d %b %Y %H:%M:%S %Z", **(params_dict.get("time_range") or {})
        )
        .call()
    )

    groupers = (
        set_groupers.validate()
        .handle_errors(task_instance_id="groupers")
        .partial(groupers=[], **(params_dict.get("groupers") or {}))
        .call()
    )

    er_client_name = (
        set_er_connection.validate()
        .handle_errors(task_instance_id="er_client_name")
        .partial(**(params_dict.get("er_client_name") or {}))
        .call()
    )

    configure_base_maps = (
        set_base_maps_pydeck.validate()
        .handle_errors(task_instance_id="configure_base_maps")
        .partial(**(params_dict.get("configure_base_maps") or {}))
        .call()
    )

    persist_mnc_tpt = (
        download_file_and_persist.validate()
        .handle_errors(task_instance_id="persist_mnc_tpt")
        .partial(
            url="https://www.dropbox.com/scl/fi/wkzd2lm1t5rzidie9wl2j/mara_north_conservancy_report_template_v4.docx?rlkey=os9ffgdk737dc60n568jfrct2&st=zo3i4ovj&dl=0",
            output_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            overwrite_existing=False,
            retries=3,
            unzip=False,
            **(params_dict.get("persist_mnc_tpt") or {}),
        )
        .call()
    )

    persist_mnc_gpkg = (
        download_file_and_persist.validate()
        .handle_errors(task_instance_id="persist_mnc_gpkg")
        .partial(
            url="https://www.dropbox.com/scl/fi/ahgr1bjv72tdeuiwf3e4h/community-conservancy.gpkg?rlkey=1bla1c9to4nj4y39nnpwpjgsx&st=hj4k3zd7&dl=0",
            output_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            overwrite_existing=False,
            retries=3,
            unzip=False,
            **(params_dict.get("persist_mnc_gpkg") or {}),
        )
        .call()
    )

    load_local_shapefiles = (
        load_geospatial_files.validate()
        .handle_errors(task_instance_id="load_local_shapefiles")
        .partial(
            config={"path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"]},
            **(params_dict.get("load_local_shapefiles") or {}),
        )
        .call()
    )

    create_custom_map_layers = (
        create_map_layers.validate()
        .handle_errors(task_instance_id="create_custom_map_layers")
        .partial(
            file_dict=load_local_shapefiles,
            style_config={
                "styles": {
                    "community_conservancy": {
                        "stroked": True,
                        "filled": False,
                        "opacity": 0.95,
                        "get_line_color": [105, 105, 105, 200],
                        "get_line_width": 2.55,
                    }
                },
                "legend": {"label": ["Conservancy boundaries"], "color": ["#696969"]},
            },
            **(params_dict.get("create_custom_map_layers") or {}),
        )
        .call()
    )

    clean_local_geo_files = (
        clean_file_keys.validate()
        .handle_errors(task_instance_id="clean_local_geo_files")
        .partial(
            file_dict=load_local_shapefiles,
            **(params_dict.get("clean_local_geo_files") or {}),
        )
        .call()
    )

    filter_aoi = (
        select_koi.validate()
        .handle_errors(task_instance_id="filter_aoi")
        .partial(
            file_dict=clean_local_geo_files,
            key_value="community_conservancy",
            **(params_dict.get("filter_aoi") or {}),
        )
        .call()
    )

    custom_text_layer = (
        make_text_layer.validate()
        .handle_errors(task_instance_id="custom_text_layer")
        .partial(
            txt_gdf=filter_aoi,
            label_column="label",
            fallback_columns=["name"],
            use_centroid=True,
            color=[0, 0, 0, 255],
            size=80,
            font_family="Arial",
            font_weight="normal",
            background=False,
            background_color=None,
            background_padding=None,
            text_anchor="middle",
            alignment_baseline="center",
            billboard=True,
            pickable=True,
            tooltip_columns=["label"],
            target_crs="epsg:4326",
            **(params_dict.get("custom_text_layer") or {}),
        )
        .call()
    )

    subject_observations = (
        get_subjectgroup_observations.validate()
        .handle_errors(task_instance_id="subject_observations")
        .partial(
            client=er_client_name,
            time_range=time_range,
            raise_on_empty=False,
            include_details=False,
            include_subjectsource_details=False,
            **(params_dict.get("subject_observations") or {}),
        )
        .call()
    )

    extract_precipitation = (
        extract_value_from_json_column.validate()
        .handle_errors(task_instance_id="extract_precipitation")
        .partial(
            df=subject_observations,
            column_name="extra__observation_details",
            field_name_options=["precipitation"],
            output_type="float",
            output_column_name="precipitation",
            **(params_dict.get("extract_precipitation") or {}),
        )
        .call()
    )

    extract_temperature = (
        extract_value_from_json_column.validate()
        .handle_errors(task_instance_id="extract_temperature")
        .partial(
            df=extract_precipitation,
            column_name="extra__observation_details",
            field_name_options=["surface_air_temperature"],
            output_type="float",
            output_column_name="temperature",
            **(params_dict.get("extract_temperature") or {}),
        )
        .call()
    )

    extract_wind_speed = (
        extract_value_from_json_column.validate()
        .handle_errors(task_instance_id="extract_wind_speed")
        .partial(
            df=extract_temperature,
            column_name="extra__observation_details",
            field_name_options=["wind_speed"],
            output_type="float",
            output_column_name="wind_speed",
            **(params_dict.get("extract_wind_speed") or {}),
        )
        .call()
    )

    extract_wind_gusts = (
        extract_value_from_json_column.validate()
        .handle_errors(task_instance_id="extract_wind_gusts")
        .partial(
            df=extract_wind_speed,
            column_name="extra__observation_details",
            field_name_options=["wind_gusts"],
            output_type="float",
            output_column_name="wind_gusts",
            **(params_dict.get("extract_wind_gusts") or {}),
        )
        .call()
    )

    extract_soil_temperature = (
        extract_value_from_json_column.validate()
        .handle_errors(task_instance_id="extract_soil_temperature")
        .partial(
            df=extract_wind_gusts,
            column_name="extra__observation_details",
            field_name_options=["soil_temperature"],
            output_type="float",
            output_column_name="soil_temperature",
            **(params_dict.get("extract_soil_temperature") or {}),
        )
        .call()
    )

    extract_relative_humidity = (
        extract_value_from_json_column.validate()
        .handle_errors(task_instance_id="extract_relative_humidity")
        .partial(
            df=extract_soil_temperature,
            column_name="extra__observation_details",
            field_name_options=["relative_humidity"],
            output_type="float",
            output_column_name="relative_humidity",
            **(params_dict.get("extract_relative_humidity") or {}),
        )
        .call()
    )

    extract_pressure = (
        extract_value_from_json_column.validate()
        .handle_errors(task_instance_id="extract_pressure")
        .partial(
            df=extract_relative_humidity,
            column_name="extra__observation_details",
            field_name_options=["atmospheric_pressure"],
            output_type="float",
            output_column_name="atmospheric_pressure",
            **(params_dict.get("extract_pressure") or {}),
        )
        .call()
    )

    extract_date = (
        extract_column_as_type.validate()
        .handle_errors(task_instance_id="extract_date")
        .partial(
            df=extract_pressure,
            column_name="fixtime",
            output_type="date",
            output_column_name="date",
            **(params_dict.get("extract_date") or {}),
        )
        .call()
    )

    rename_grouper_columns = (
        map_columns.validate()
        .handle_errors(task_instance_id="rename_grouper_columns")
        .partial(
            df=extract_date,
            drop_columns=[],
            retain_columns=[],
            rename_columns={"extra__subject__name": "weather_station"},
            **(params_dict.get("rename_grouper_columns") or {}),
        )
        .call()
    )

    df_with_temporal_index = (
        add_temporal_index.validate()
        .handle_errors(task_instance_id="df_with_temporal_index")
        .partial(
            df=rename_grouper_columns,
            time_col="fixtime",
            groupers=groupers,
            **(params_dict.get("df_with_temporal_index") or {}),
        )
        .call()
    )

    daily_weather = (
        summarize_df.validate()
        .handle_errors(task_instance_id="daily_weather")
        .partial(
            df=df_with_temporal_index,
            groupby_cols=["weather_station", "date"],
            summary_params=[
                {
                    "display_name": "precipitation",
                    "aggregator": "sum",
                    "column": "precipitation",
                },
                {
                    "display_name": "temperature",
                    "aggregator": "mean",
                    "column": "temperature",
                },
                {
                    "display_name": "wind_speed",
                    "aggregator": "mean",
                    "column": "wind_speed",
                },
                {
                    "display_name": "wind_gusts",
                    "aggregator": "max",
                    "column": "wind_gusts",
                },
                {
                    "display_name": "soil_temperature",
                    "aggregator": "mean",
                    "column": "soil_temperature",
                },
                {
                    "display_name": "relative_humidity",
                    "aggregator": "mean",
                    "column": "relative_humidity",
                },
                {
                    "display_name": "atmospheric_pressure",
                    "aggregator": "mean",
                    "column": "atmospheric_pressure",
                },
            ],
            reset_index=True,
            **(params_dict.get("daily_weather") or {}),
        )
        .call()
    )

    persist_daily_weather_summary = (
        persist_df.validate()
        .handle_errors(task_instance_id="persist_daily_weather_summary")
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetype="csv",
            df=daily_weather,
            filename="weather_summary_table",
            **(params_dict.get("persist_daily_weather_summary") or {}),
        )
        .call()
    )

    precipitation_chart = (
        draw_line_chart.validate()
        .handle_errors(task_instance_id="precipitation_chart")
        .partial(
            dataframe=daily_weather,
            x_column="date",
            y_column="precipitation",
            category_column="weather_station",
            line_kwargs={"shape": "linear"},
            layout_kwargs={
                "title": None,
                "title_x": 0.01,
                "title_y": 0.95,
                "showlegend": True,
                "fontsize": 12,
                "fontcolor": "#2c3e50",
                "plot_bgcolor": "#f5f5f5",
                "xaxis": {
                    "title": "Date",
                    "showgrid": True,
                    "gridcolor": "#e0e0e0",
                    "gridwidth": 1,
                    "tickformat": "%Y-%m-%d",
                    "tickangle": -45,
                    "rangemode": "auto",
                },
                "yaxis": {"title": "Precipitation (mm)", "tickformat": ".1f"},
                "legend_title": "Weather Station",
                "hovermode": "x unified",
            },
            **(params_dict.get("precipitation_chart") or {}),
        )
        .call()
    )

    persist_precipitation = (
        persist_text.validate()
        .handle_errors(task_instance_id="persist_precipitation")
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            text=precipitation_chart,
            filename="precipitation_readings_over_time",
            **(params_dict.get("persist_precipitation") or {}),
        )
        .call()
    )

    precipitation_png = (
        html_to_png.validate()
        .handle_errors(task_instance_id="precipitation_png")
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={"wait_for_timeout": 200},
            html_path=persist_precipitation,
            **(params_dict.get("precipitation_png") or {}),
        )
        .call()
    )

    temperature_chart = (
        draw_line_chart.validate()
        .handle_errors(task_instance_id="temperature_chart")
        .partial(
            dataframe=daily_weather,
            x_column="date",
            y_column="temperature",
            category_column="weather_station",
            line_kwargs={"shape": "linear"},
            layout_kwargs={
                "title": None,
                "title_x": 0.01,
                "title_y": 0.95,
                "showlegend": True,
                "fontsize": 12,
                "fontcolor": "#2c3e50",
                "plot_bgcolor": "#f5f5f5",
                "xaxis": {
                    "title": "Date",
                    "tickformat": "%Y-%m-%d",
                    "tickangle": -45,
                    "rangemode": "auto",
                },
                "yaxis": {"title": "Average Temperature (°C)", "tickformat": ".1f"},
                "legend_title": "Weather Station",
                "hovermode": "x unified",
            },
            **(params_dict.get("temperature_chart") or {}),
        )
        .call()
    )

    persist_temperature = (
        persist_text.validate()
        .handle_errors(task_instance_id="persist_temperature")
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            text=temperature_chart,
            filename="temperature_readings_over_time",
            **(params_dict.get("persist_temperature") or {}),
        )
        .call()
    )

    temperature_png = (
        html_to_png.validate()
        .handle_errors(task_instance_id="temperature_png")
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={"wait_for_timeout": 200},
            html_path=persist_temperature,
            **(params_dict.get("temperature_png") or {}),
        )
        .call()
    )

    wind_speed_chart = (
        draw_line_chart.validate()
        .handle_errors(task_instance_id="wind_speed_chart")
        .partial(
            dataframe=daily_weather,
            x_column="date",
            y_column="wind_speed",
            category_column="weather_station",
            line_kwargs={"shape": "linear"},
            layout_kwargs={
                "title": None,
                "title_x": 0.01,
                "title_y": 0.95,
                "showlegend": True,
                "fontsize": 12,
                "fontcolor": "#2c3e50",
                "plot_bgcolor": "#f5f5f5",
                "xaxis": {
                    "title": "Date",
                    "tickformat": "%Y-%m-%d",
                    "tickangle": -45,
                    "rangemode": "auto",
                },
                "yaxis": {"title": "Average wind speed", "tickformat": ".1f"},
                "legend_title": "Weather Station",
                "hovermode": "x unified",
            },
            **(params_dict.get("wind_speed_chart") or {}),
        )
        .call()
    )

    persist_wind_speed = (
        persist_text.validate()
        .handle_errors(task_instance_id="persist_wind_speed")
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            text=wind_speed_chart,
            filename="wind_speed_readings_over_time",
            **(params_dict.get("persist_wind_speed") or {}),
        )
        .call()
    )

    wind_speed_png = (
        html_to_png.validate()
        .handle_errors(task_instance_id="wind_speed_png")
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={"wait_for_timeout": 200},
            html_path=persist_wind_speed,
            **(params_dict.get("wind_speed_png") or {}),
        )
        .call()
    )

    wind_gusts_chart = (
        draw_line_chart.validate()
        .handle_errors(task_instance_id="wind_gusts_chart")
        .partial(
            dataframe=daily_weather,
            x_column="date",
            y_column="wind_gusts",
            category_column="weather_station",
            line_kwargs={"shape": "linear"},
            layout_kwargs={
                "title": None,
                "title_x": 0.01,
                "title_y": 0.95,
                "showlegend": True,
                "fontsize": 12,
                "fontcolor": "#2c3e50",
                "plot_bgcolor": "#f5f5f5",
                "xaxis": {
                    "title": "Date",
                    "tickformat": "%Y-%m-%d",
                    "tickangle": -45,
                    "rangemode": "auto",
                },
                "yaxis": {"title": "Max wind gusts", "tickformat": ".1f"},
                "legend_title": "Weather Station",
                "hovermode": "x unified",
            },
            **(params_dict.get("wind_gusts_chart") or {}),
        )
        .call()
    )

    persist_wind_gusts = (
        persist_text.validate()
        .handle_errors(task_instance_id="persist_wind_gusts")
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            text=wind_gusts_chart,
            filename="wind_gusts_readings_over_time",
            **(params_dict.get("persist_wind_gusts") or {}),
        )
        .call()
    )

    wind_gusts_png = (
        html_to_png.validate()
        .handle_errors(task_instance_id="wind_gusts_png")
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={"wait_for_timeout": 200},
            html_path=persist_wind_gusts,
            **(params_dict.get("wind_gusts_png") or {}),
        )
        .call()
    )

    soil_temp_chart = (
        draw_line_chart.validate()
        .handle_errors(task_instance_id="soil_temp_chart")
        .partial(
            dataframe=daily_weather,
            x_column="date",
            y_column="soil_temperature",
            category_column="weather_station",
            line_kwargs={"shape": "linear"},
            layout_kwargs={
                "title": None,
                "title_x": 0.01,
                "title_y": 0.95,
                "showlegend": True,
                "fontsize": 12,
                "fontcolor": "#2c3e50",
                "plot_bgcolor": "#f5f5f5",
                "xaxis": {
                    "title": "Date",
                    "tickformat": "%Y-%m-%d",
                    "tickangle": -45,
                    "rangemode": "auto",
                },
                "yaxis": {"title": "Average Temperature (°C)", "tickformat": ".1f"},
                "legend_title": "Weather Station",
                "hovermode": "x unified",
            },
            **(params_dict.get("soil_temp_chart") or {}),
        )
        .call()
    )

    persist_soil_temp = (
        persist_text.validate()
        .handle_errors(task_instance_id="persist_soil_temp")
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            text=soil_temp_chart,
            filename="soil_temperature_readings_over_time",
            **(params_dict.get("persist_soil_temp") or {}),
        )
        .call()
    )

    soil_temp_png = (
        html_to_png.validate()
        .handle_errors(task_instance_id="soil_temp_png")
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={"wait_for_timeout": 200},
            html_path=persist_soil_temp,
            **(params_dict.get("soil_temp_png") or {}),
        )
        .call()
    )

    rel_humidity_chart = (
        draw_line_chart.validate()
        .handle_errors(task_instance_id="rel_humidity_chart")
        .partial(
            dataframe=daily_weather,
            x_column="date",
            y_column="relative_humidity",
            category_column="weather_station",
            line_kwargs={"shape": "linear"},
            layout_kwargs={
                "title": None,
                "title_x": 0.01,
                "title_y": 0.95,
                "showlegend": True,
                "fontsize": 12,
                "fontcolor": "#2c3e50",
                "plot_bgcolor": "#f5f5f5",
                "xaxis": {
                    "title": "Date",
                    "tickformat": "%Y-%m-%d",
                    "tickangle": -45,
                    "rangemode": "auto",
                },
                "yaxis": {"title": "Average humidity", "tickformat": ".1f"},
                "legend_title": "Weather Station",
                "hovermode": "x unified",
            },
            **(params_dict.get("rel_humidity_chart") or {}),
        )
        .call()
    )

    persist_rel_humidity = (
        persist_text.validate()
        .handle_errors(task_instance_id="persist_rel_humidity")
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            text=rel_humidity_chart,
            filename="relative_humidity_readings_over_time",
            **(params_dict.get("persist_rel_humidity") or {}),
        )
        .call()
    )

    rel_humidity_png = (
        html_to_png.validate()
        .handle_errors(task_instance_id="rel_humidity_png")
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={"wait_for_timeout": 200},
            html_path=persist_rel_humidity,
            **(params_dict.get("rel_humidity_png") or {}),
        )
        .call()
    )

    pressure_chart = (
        draw_line_chart.validate()
        .handle_errors(task_instance_id="pressure_chart")
        .partial(
            dataframe=daily_weather,
            x_column="date",
            y_column="atmospheric_pressure",
            category_column="weather_station",
            line_kwargs={"shape": "linear"},
            layout_kwargs={
                "title": None,
                "title_x": 0.01,
                "title_y": 0.95,
                "showlegend": True,
                "fontsize": 12,
                "fontcolor": "#2c3e50",
                "plot_bgcolor": "#f5f5f5",
                "xaxis": {
                    "title": "Date",
                    "tickformat": "%Y-%m-%d",
                    "tickangle": -45,
                    "rangemode": "auto",
                },
                "yaxis": {"title": "Average pressure", "tickformat": ".1f"},
                "legend_title": "Weather Station",
                "hovermode": "x unified",
            },
            **(params_dict.get("pressure_chart") or {}),
        )
        .call()
    )

    persist_pressure = (
        persist_text.validate()
        .handle_errors(task_instance_id="persist_pressure")
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            text=pressure_chart,
            filename="atmospheric_pressure_readings_over_time",
            **(params_dict.get("persist_pressure") or {}),
        )
        .call()
    )

    pressure_png = (
        html_to_png.validate()
        .handle_errors(task_instance_id="pressure_png")
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={"wait_for_timeout": 200},
            html_path=persist_pressure,
            **(params_dict.get("pressure_png") or {}),
        )
        .call()
    )

    get_events_data = (
        get_events.validate()
        .handle_errors(task_instance_id="get_events_data")
        .partial(
            client=er_client_name,
            time_range=time_range,
            event_columns=[
                "id",
                "time",
                "event_type",
                "event_category",
                "reported_by",
                "serial_number",
                "geometry",
                "created_at",
                "event_details",
            ],
            event_types=[],
            raise_on_empty=True,
            include_details=True,
            include_updates=False,
            include_related_events=False,
            include_null_geometry=False,
            **(params_dict.get("get_events_data") or {}),
        )
        .call()
    )

    extract_event_date = (
        extract_column_as_type.validate()
        .handle_errors(task_instance_id="extract_event_date")
        .partial(
            df=get_events_data,
            column_name="created_at",
            output_type="date",
            output_column_name="date",
            **(params_dict.get("extract_event_date") or {}),
        )
        .call()
    )

    events_wtemporal = (
        add_temporal_index.validate()
        .handle_errors(task_instance_id="events_wtemporal")
        .partial(
            df=extract_event_date,
            time_col="created_at",
            groupers=groupers,
            **(params_dict.get("events_wtemporal") or {}),
        )
        .call()
    )

    exclude_event_type_values = (
        filter_by_value.validate()
        .handle_errors(task_instance_id="exclude_event_type_values")
        .partial(
            df=events_wtemporal,
            column_name="event_type",
            value=["distancecountwildlife_rep", "distancecountpatrol_rep"],
            **(params_dict.get("exclude_event_type_values") or {}),
        )
        .call()
    )

    total_events_recorded = (
        summarize_df.validate()
        .handle_errors(task_instance_id="total_events_recorded")
        .partial(
            groupby_cols=["date"],
            summary_params=[
                {
                    "display_name": "no_of_events",
                    "aggregator": "nunique",
                    "column": "id",
                }
            ],
            reset_index=True,
            df=exclude_event_type_values,
            **(params_dict.get("total_events_recorded") or {}),
        )
        .call()
    )

    add_total_events_row = (
        add_totals_row.validate()
        .handle_errors(task_instance_id="add_total_events_row")
        .partial(
            label_col=["date"],
            label="Total",
            df=total_events_recorded,
            **(params_dict.get("add_total_events_row") or {}),
        )
        .call()
    )

    persist_tevents_df = (
        persist_df.validate()
        .handle_errors(task_instance_id="persist_tevents_df")
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetype="csv",
            df=add_total_events_row,
            filename="total_events_recorded",
            **(params_dict.get("persist_tevents_df") or {}),
        )
        .call()
    )

    draw_events_chart = (
        draw_line_chart.validate()
        .handle_errors(task_instance_id="draw_events_chart")
        .partial(
            dataframe=total_events_recorded,
            x_column="date",
            y_column="no_of_events",
            category_column=None,
            line_kwargs={"shape": "linear", "color": "lightsteelblue"},
            layout_kwargs={
                "title": None,
                "title_x": 0.01,
                "title_y": 0.95,
                "showlegend": False,
                "fontsize": 12,
                "fontcolor": "#2c3e50",
                "plot_bgcolor": "#f5f5f5",
                "xaxis": {
                    "title": "Date",
                    "tickformat": "%Y-%m-%d",
                    "tickangle": -45,
                    "rangemode": "auto",
                },
                "yaxis": {"title": "Number of events", "tickformat": ".1f"},
                "hovermode": "x unified",
            },
            **(params_dict.get("draw_events_chart") or {}),
        )
        .call()
    )

    persist_total_events = (
        persist_text.validate()
        .handle_errors(task_instance_id="persist_total_events")
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            text=draw_events_chart,
            filename="total_events_recorded",
            **(params_dict.get("persist_total_events") or {}),
        )
        .call()
    )

    mnc_events_dashboard = (
        gather_dashboard.validate()
        .handle_errors(task_instance_id="mnc_events_dashboard")
        .partial(
            details=workflow_details,
            widgets=[],
            time_range=time_range,
            groupers=groupers,
            **(params_dict.get("mnc_events_dashboard") or {}),
        )
        .call()
    )

    return mnc_events_dashboard
