# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details

# ruff: noqa: E402

"""WARNING: This file is generated in a testing context and should not be used in production.
Lines specific to the testing context are marked with a test tube emoji (🧪) to indicate
that they would not be included (or would be different) in the production version of this file.
"""

import json
import os
import warnings  # 🧪

from ecoscope_workflows_core.graph import DependsOn, Graph, Node
from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.groupby import set_groupers as set_groupers
from ecoscope_workflows_core.tasks.io import set_er_connection as set_er_connection
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_core.tasks.transformation import filter_df as filter_df
from ecoscope_workflows_core.testing import create_task_magicmock  # 🧪
from ecoscope_workflows_ext_custom.tasks.io import load_df as load_df
from ecoscope_workflows_ext_custom.tasks.results import (
    set_base_maps_pydeck as set_base_maps_pydeck,
)
from ecoscope_workflows_ext_mnc.tasks import (
    create_gdf_from_dict as create_gdf_from_dict,
)
from ecoscope_workflows_ext_ste.tasks import (
    annotate_gdf_dict_with_geom_type as annotate_gdf_dict_with_geom_type,
)
from ecoscope_workflows_ext_ste.tasks import (
    create_custom_text_layer as create_custom_text_layer,
)
from ecoscope_workflows_ext_ste.tasks import (
    create_deckgl_layer_from_gdf as create_deckgl_layer_from_gdf,
)
from ecoscope_workflows_ext_ste.tasks import (
    create_deckgl_layers_from_gdf_dict as create_deckgl_layers_from_gdf_dict,
)
from ecoscope_workflows_ext_ste.tasks import (
    fetch_and_persist_file as fetch_and_persist_file,
)
from ecoscope_workflows_ext_ste.tasks import get_gdf_geom_type as get_gdf_geom_type
from ecoscope_workflows_ext_ste.tasks import split_gdf_by_column as split_gdf_by_column

get_subjectgroup_observations = create_task_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_ecoscope.tasks.io",  # 🧪
    func_name="get_subjectgroup_observations",  # 🧪
)  # 🧪
from ecoscope_workflows_core.tasks.groupby import groupbykey as groupbykey
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.skip import (
    all_keyed_iterables_are_skips as all_keyed_iterables_are_skips,
)
from ecoscope_workflows_core.tasks.transformation import (
    add_temporal_index as add_temporal_index,
)
from ecoscope_workflows_core.tasks.transformation import (
    extract_column_as_type as extract_column_as_type,
)
from ecoscope_workflows_core.tasks.transformation import (
    extract_value_from_json_column as extract_value_from_json_column,
)
from ecoscope_workflows_core.tasks.transformation import map_columns as map_columns
from ecoscope_workflows_ext_custom.tasks.io import html_to_png as html_to_png
from ecoscope_workflows_ext_ecoscope.tasks.analysis import summarize_df as summarize_df
from ecoscope_workflows_ext_ecoscope.tasks.io import persist_df as persist_df
from ecoscope_workflows_ext_ecoscope.tasks.results import (
    draw_line_chart as draw_line_chart,
)

from ..params import Params


def main(params: Params):
    warnings.warn("This test script should not be used in production!")  # 🧪

    params_dict = json.loads(params.model_dump_json(exclude_unset=True))

    dependencies = {
        "workflow_details": [],
        "time_range": [],
        "groupers": [],
        "er_client_name": [],
        "configure_base_maps": [],
        "persist_mnc_tpt": [],
        "persist_mnc_gpkg": [],
        "download_mnc_parcels": [],
        "load_comm_shp": ["persist_mnc_gpkg"],
        "split_gdf_by_zone": ["load_comm_shp"],
        "annotate_comm_gdf_dict": ["split_gdf_by_zone"],
        "create_mnc_styled_layers": ["annotate_comm_gdf_dict"],
        "create_conservancy_boundaries": ["annotate_comm_gdf_dict"],
        "conservancy_gdf": ["split_gdf_by_zone"],
        "overall_grazing_zones": ["load_comm_shp"],
        "conservancy_text_layer": ["conservancy_gdf"],
        "load_mnc_parcels": ["download_mnc_parcels"],
        "assign_mnc_geom": ["load_mnc_parcels"],
        "create_mnc_parcels_layers": ["assign_mnc_geom"],
        "parcels_text_layer": ["load_mnc_parcels"],
        "subject_observations": ["er_client_name", "time_range"],
        "extract_precipitation": ["subject_observations"],
        "extract_temperature": ["extract_precipitation"],
        "extract_wind_speed": ["extract_temperature"],
        "extract_wind_gusts": ["extract_wind_speed"],
        "extract_soil_temperature": ["extract_wind_gusts"],
        "extract_relative_humidity": ["extract_soil_temperature"],
        "extract_pressure": ["extract_relative_humidity"],
        "extract_date": ["extract_pressure"],
        "rename_grouper_columns": ["extract_date"],
        "df_with_temporal_index": ["rename_grouper_columns", "groupers"],
        "daily_weather": ["df_with_temporal_index"],
        "persist_weather_summary": ["daily_weather"],
        "precipitation_chart": ["daily_weather"],
        "persist_precipitation": ["precipitation_chart"],
        "temperature_chart": ["daily_weather"],
        "persist_temperature": ["temperature_chart"],
        "wind_speed_chart": ["daily_weather"],
        "persist_wind_speed": ["wind_speed_chart"],
        "wind_gusts_chart": ["daily_weather"],
        "persist_wind_gusts": ["wind_gusts_chart"],
        "soil_temp_chart": ["daily_weather"],
        "persist_soil_temp": ["soil_temp_chart"],
        "rel_humidity_chart": ["daily_weather"],
        "persist_rel_humidity": ["rel_humidity_chart"],
        "pressure_chart": ["daily_weather"],
        "persist_pressure": ["pressure_chart"],
        "group_weather_html": [
            "persist_precipitation",
            "persist_temperature",
            "persist_wind_speed",
            "persist_wind_gusts",
            "persist_soil_temp",
            "persist_rel_humidity",
            "persist_pressure",
        ],
        "convert_weather_png": ["group_weather_html"],
        "mnc_events_dashboard": ["workflow_details", "time_range", "groupers"],
    }

    nodes = {
        "workflow_details": Node(
            async_task=set_workflow_details.validate()
            .set_task_instance_id("workflow_details")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("workflow_details") or {}),
            method="call",
        ),
        "time_range": Node(
            async_task=set_time_range.validate()
            .set_task_instance_id("time_range")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "time_format": "%d %b %Y %H:%M:%S %Z",
                "timezone": {
                    "label": "UTC",
                    "tzCode": "UTC",
                    "name": "UTC",
                    "utc_offset": "+00:00",
                },
            }
            | (params_dict.get("time_range") or {}),
            method="call",
        ),
        "groupers": Node(
            async_task=set_groupers.validate()
            .set_task_instance_id("groupers")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("groupers") or {}),
            method="call",
        ),
        "er_client_name": Node(
            async_task=set_er_connection.validate()
            .set_task_instance_id("er_client_name")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("er_client_name") or {}),
            method="call",
        ),
        "configure_base_maps": Node(
            async_task=set_base_maps_pydeck.validate()
            .set_task_instance_id("configure_base_maps")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("configure_base_maps") or {}),
            method="call",
        ),
        "persist_mnc_tpt": Node(
            async_task=fetch_and_persist_file.validate()
            .set_task_instance_id("persist_mnc_tpt")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "url": "https://www.dropbox.com/scl/fi/zwb5d8nxfwqhjikjybmst/mara_north_template_2.docx?rlkey=it5d7a6382xyzgelh0cuy2xsy&st=zyi1ggdd&dl=0",
                "output_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "overwrite_existing": False,
                "retries": 3,
                "unzip": False,
            }
            | (params_dict.get("persist_mnc_tpt") or {}),
            method="call",
        ),
        "persist_mnc_gpkg": Node(
            async_task=fetch_and_persist_file.validate()
            .set_task_instance_id("persist_mnc_gpkg")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "url": "https://www.dropbox.com/scl/fi/14rcy4lkwp7xgewj3xf7k/mnc_conservancy.gpkg?rlkey=mtqo7ivxrnvjonm2z1zez6h6f&st=55vxskq6&dl=0",
                "output_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "overwrite_existing": False,
                "retries": 3,
                "unzip": False,
            }
            | (params_dict.get("persist_mnc_gpkg") or {}),
            method="call",
        ),
        "download_mnc_parcels": Node(
            async_task=fetch_and_persist_file.validate()
            .set_task_instance_id("download_mnc_parcels")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "url": "https://www.dropbox.com/scl/fi/33rdzy896rh91gtkfs2j3/mnc_across_the_river_parcels.gpkg?rlkey=xima1v0rozc0h9h78esfogx6q&st=o3gkk5p1&dl=0",
                "output_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "overwrite_existing": False,
                "retries": 3,
                "unzip": False,
            }
            | (params_dict.get("download_mnc_parcels") or {}),
            method="call",
        ),
        "load_comm_shp": Node(
            async_task=load_df.validate()
            .set_task_instance_id("load_comm_shp")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "file_path": DependsOn("persist_mnc_gpkg"),
                "layer": None,
                "deserialize_json": False,
            }
            | (params_dict.get("load_comm_shp") or {}),
            method="call",
        ),
        "split_gdf_by_zone": Node(
            async_task=split_gdf_by_column.validate()
            .set_task_instance_id("split_gdf_by_zone")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "gdf": DependsOn("load_comm_shp"),
                "column": "grazing_zone",
            }
            | (params_dict.get("split_gdf_by_zone") or {}),
            method="call",
        ),
        "annotate_comm_gdf_dict": Node(
            async_task=annotate_gdf_dict_with_geom_type.validate()
            .set_task_instance_id("annotate_comm_gdf_dict")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "gdf_dict": DependsOn("split_gdf_by_zone"),
            }
            | (params_dict.get("annotate_comm_gdf_dict") or {}),
            method="call",
        ),
        "create_mnc_styled_layers": Node(
            async_task=create_deckgl_layers_from_gdf_dict.validate()
            .set_task_instance_id("create_mnc_styled_layers")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "gdf_dict": DependsOn("annotate_comm_gdf_dict"),
                "styles": {
                    "Conservancy": {
                        "extruded": False,
                        "get_fill_color": [
                            105,
                            105,
                            105,
                        ],
                        "get_line_color": [
                            105,
                            105,
                            105,
                        ],
                        "get_line_width": 2.25,
                        "stroked": True,
                        "filled": False,
                        "opacity": 0.95,
                    },
                    "Conservancy Herd Zone": {
                        "extruded": False,
                        "get_fill_color": [
                            173,
                            255,
                            47,
                        ],
                        "get_line_color": [
                            173,
                            255,
                            47,
                        ],
                        "get_line_width": 2.25,
                        "stroked": True,
                        "filled": True,
                        "opacity": 0.35,
                    },
                    "Grazing Zone 1": {
                        "extruded": False,
                        "get_fill_color": [
                            85,
                            107,
                            47,
                        ],
                        "get_line_color": [
                            85,
                            107,
                            47,
                        ],
                        "get_line_width": 2.25,
                        "stroked": True,
                        "filled": True,
                        "opacity": 0.35,
                    },
                    "Grazing Zone 2": {
                        "extruded": False,
                        "get_fill_color": [
                            0,
                            139,
                            139,
                        ],
                        "get_line_color": [
                            0,
                            139,
                            139,
                        ],
                        "get_line_width": 2.25,
                        "stroked": True,
                        "filled": True,
                        "opacity": 0.35,
                    },
                    "Grazing Zone 3": {
                        "extruded": False,
                        "get_fill_color": [
                            0,
                            100,
                            0,
                        ],
                        "get_line_color": [
                            0,
                            100,
                            0,
                        ],
                        "get_line_width": 2.25,
                        "stroked": True,
                        "filled": True,
                        "opacity": 0.35,
                    },
                    "Grazing Zone 4": {
                        "extruded": False,
                        "get_fill_color": [
                            143,
                            188,
                            139,
                        ],
                        "get_line_color": [
                            143,
                            188,
                            139,
                        ],
                        "get_line_width": 2.25,
                        "stroked": True,
                        "filled": True,
                        "opacity": 0.35,
                    },
                },
                "legends": {
                    "title": "Community Areas",
                    "values": [
                        {
                            "label": "Conservancy boundaries",
                            "color": "#696969",
                        },
                        {
                            "label": "Conservancy herd zone",
                            "color": "#adff2f",
                        },
                        {
                            "label": "Grazing zone 1",
                            "color": "#556b2f",
                        },
                        {
                            "label": "Grazing zone 2",
                            "color": "#008b8b",
                        },
                        {
                            "label": "Grazing zone 3",
                            "color": "#006400",
                        },
                        {
                            "label": "Grazing zone 4",
                            "color": "#8fbc8b",
                        },
                    ],
                },
            }
            | (params_dict.get("create_mnc_styled_layers") or {}),
            method="call",
        ),
        "create_conservancy_boundaries": Node(
            async_task=create_deckgl_layers_from_gdf_dict.validate()
            .set_task_instance_id("create_conservancy_boundaries")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "gdf_dict": DependsOn("annotate_comm_gdf_dict"),
                "styles": {
                    "Conservancy": {
                        "extruded": False,
                        "get_fill_color": [
                            105,
                            105,
                            105,
                        ],
                        "get_line_color": [
                            105,
                            105,
                            105,
                        ],
                        "get_line_width": 2.25,
                        "stroked": True,
                        "filled": False,
                        "opacity": 0.95,
                    },
                },
                "legends": {
                    "title": "Community Areas",
                    "values": [
                        {
                            "label": "Conservancy boundaries",
                            "color": "#696969",
                        },
                    ],
                },
            }
            | (params_dict.get("create_conservancy_boundaries") or {}),
            method="call",
        ),
        "conservancy_gdf": Node(
            async_task=create_gdf_from_dict.validate()
            .set_task_instance_id("conservancy_gdf")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "gdf_dict": DependsOn("split_gdf_by_zone"),
                "key": "Conservancy",
            }
            | (params_dict.get("conservancy_gdf") or {}),
            method="call",
        ),
        "overall_grazing_zones": Node(
            async_task=filter_df.validate()
            .set_task_instance_id("overall_grazing_zones")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "column_name": "grazing_zone",
                "op": "ne",
                "value": "Conservancy",
                "df": DependsOn("load_comm_shp"),
                "reset_index": False,
            }
            | (params_dict.get("overall_grazing_zones") or {}),
            method="call",
        ),
        "conservancy_text_layer": Node(
            async_task=create_custom_text_layer.validate()
            .set_task_instance_id("conservancy_text_layer")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "geodataframe": DependsOn("conservancy_gdf"),
                "layer_style": {
                    "get_text": "name",
                    "get_color": [
                        0,
                        0,
                        0,
                        255,
                    ],
                    "get_size": 1500,
                    "size_units": "meters",
                    "size_min_pixels": 70,
                    "size_max_pixels": 100,
                    "size_scale": 2.25,
                    "font_family": "Calibri",
                    "font_weight": "700",
                    "get_text_anchor": "middle",
                    "get_alignment_baseline": "center",
                    "billboard": True,
                    "background_padding": [
                        4,
                        8,
                    ],
                    "pickable": True,
                    "auto_highlight": False,
                },
                "use_centroid": True,
                "legend": None,
            }
            | (params_dict.get("conservancy_text_layer") or {}),
            method="call",
        ),
        "load_mnc_parcels": Node(
            async_task=load_df.validate()
            .set_task_instance_id("load_mnc_parcels")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "file_path": DependsOn("download_mnc_parcels"),
                "layer": None,
                "deserialize_json": False,
            }
            | (params_dict.get("load_mnc_parcels") or {}),
            method="call",
        ),
        "assign_mnc_geom": Node(
            async_task=get_gdf_geom_type.validate()
            .set_task_instance_id("assign_mnc_geom")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "gdf": DependsOn("load_mnc_parcels"),
            }
            | (params_dict.get("assign_mnc_geom") or {}),
            method="call",
        ),
        "create_mnc_parcels_layers": Node(
            async_task=create_deckgl_layer_from_gdf.validate()
            .set_task_instance_id("create_mnc_parcels_layers")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "gdf": DependsOn("assign_mnc_geom"),
                "style": {
                    "extruded": False,
                    "get_fill_color": [
                        100,
                        149,
                        237,
                    ],
                    "get_line_color": [
                        100,
                        149,
                        237,
                    ],
                    "get_line_width": 2.25,
                    "stroked": True,
                    "filled": True,
                    "opacity": 0.35,
                },
                "legend": {
                    "title": "Parcels",
                    "values": [
                        {
                            "label": "Parcels across river",
                            "color": "#6495ed",
                        },
                    ],
                },
            }
            | (params_dict.get("create_mnc_parcels_layers") or {}),
            method="call",
        ),
        "parcels_text_layer": Node(
            async_task=create_custom_text_layer.validate()
            .set_task_instance_id("parcels_text_layer")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "geodataframe": DependsOn("load_mnc_parcels"),
                "layer_style": {
                    "get_text": "name",
                    "get_color": [
                        0,
                        0,
                        0,
                        255,
                    ],
                    "get_size": 1500,
                    "size_units": "meters",
                    "size_min_pixels": 70,
                    "size_max_pixels": 100,
                    "size_scale": 2.25,
                    "font_family": "Calibri",
                    "font_weight": "700",
                    "get_text_anchor": "middle",
                    "get_alignment_baseline": "center",
                    "billboard": True,
                    "background_padding": [
                        4,
                        8,
                    ],
                    "pickable": True,
                    "auto_highlight": False,
                },
                "use_centroid": True,
                "legend": None,
            }
            | (params_dict.get("parcels_text_layer") or {}),
            method="call",
        ),
        "subject_observations": Node(
            async_task=get_subjectgroup_observations.validate()
            .set_task_instance_id("subject_observations")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "client": DependsOn("er_client_name"),
                "time_range": DependsOn("time_range"),
                "raise_on_empty": False,
                "include_details": False,
                "include_subjectsource_details": False,
                "subject_group_name": "ER2ER - From GMMF",
            }
            | (params_dict.get("subject_observations") or {}),
            method="call",
        ),
        "extract_precipitation": Node(
            async_task=extract_value_from_json_column.validate()
            .set_task_instance_id("extract_precipitation")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("subject_observations"),
                "column_name": "extra__observation_details",
                "field_name_options": [
                    "precipitation",
                ],
                "output_type": "float",
                "output_column_name": "precipitation",
            }
            | (params_dict.get("extract_precipitation") or {}),
            method="call",
        ),
        "extract_temperature": Node(
            async_task=extract_value_from_json_column.validate()
            .set_task_instance_id("extract_temperature")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("extract_precipitation"),
                "column_name": "extra__observation_details",
                "field_name_options": [
                    "surface_air_temperature",
                ],
                "output_type": "float",
                "output_column_name": "temperature",
            }
            | (params_dict.get("extract_temperature") or {}),
            method="call",
        ),
        "extract_wind_speed": Node(
            async_task=extract_value_from_json_column.validate()
            .set_task_instance_id("extract_wind_speed")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("extract_temperature"),
                "column_name": "extra__observation_details",
                "field_name_options": [
                    "wind_speed",
                ],
                "output_type": "float",
                "output_column_name": "wind_speed",
            }
            | (params_dict.get("extract_wind_speed") or {}),
            method="call",
        ),
        "extract_wind_gusts": Node(
            async_task=extract_value_from_json_column.validate()
            .set_task_instance_id("extract_wind_gusts")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("extract_wind_speed"),
                "column_name": "extra__observation_details",
                "field_name_options": [
                    "wind_gusts",
                ],
                "output_type": "float",
                "output_column_name": "wind_gusts",
            }
            | (params_dict.get("extract_wind_gusts") or {}),
            method="call",
        ),
        "extract_soil_temperature": Node(
            async_task=extract_value_from_json_column.validate()
            .set_task_instance_id("extract_soil_temperature")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("extract_wind_gusts"),
                "column_name": "extra__observation_details",
                "field_name_options": [
                    "soil_temperature",
                ],
                "output_type": "float",
                "output_column_name": "soil_temperature",
            }
            | (params_dict.get("extract_soil_temperature") or {}),
            method="call",
        ),
        "extract_relative_humidity": Node(
            async_task=extract_value_from_json_column.validate()
            .set_task_instance_id("extract_relative_humidity")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("extract_soil_temperature"),
                "column_name": "extra__observation_details",
                "field_name_options": [
                    "relative_humidity",
                ],
                "output_type": "float",
                "output_column_name": "relative_humidity",
            }
            | (params_dict.get("extract_relative_humidity") or {}),
            method="call",
        ),
        "extract_pressure": Node(
            async_task=extract_value_from_json_column.validate()
            .set_task_instance_id("extract_pressure")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("extract_relative_humidity"),
                "column_name": "extra__observation_details",
                "field_name_options": [
                    "atmospheric_pressure",
                ],
                "output_type": "float",
                "output_column_name": "atmospheric_pressure",
            }
            | (params_dict.get("extract_pressure") or {}),
            method="call",
        ),
        "extract_date": Node(
            async_task=extract_column_as_type.validate()
            .set_task_instance_id("extract_date")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("extract_pressure"),
                "column_name": "fixtime",
                "output_type": "date",
                "output_column_name": "date",
            }
            | (params_dict.get("extract_date") or {}),
            method="call",
        ),
        "rename_grouper_columns": Node(
            async_task=map_columns.validate()
            .set_task_instance_id("rename_grouper_columns")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("extract_date"),
                "rename_columns": {
                    "extra__subject__name": "weather_station",
                },
            }
            | (params_dict.get("rename_grouper_columns") or {}),
            method="call",
        ),
        "df_with_temporal_index": Node(
            async_task=add_temporal_index.validate()
            .set_task_instance_id("df_with_temporal_index")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("rename_grouper_columns"),
                "time_col": "fixtime",
                "cast_to_datetime": True,
                "groupers": DependsOn("groupers"),
                "format": "mixed",
            }
            | (params_dict.get("df_with_temporal_index") or {}),
            method="call",
        ),
        "daily_weather": Node(
            async_task=summarize_df.validate()
            .set_task_instance_id("daily_weather")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("df_with_temporal_index"),
                "groupby_cols": [
                    "weather_station",
                    "date",
                ],
                "summary_params": [
                    {
                        "display_name": "precipitation",
                        "aggregator": "sum",
                        "column": "precipitation",
                    },
                    {
                        "display_name": "temperature",
                        "aggregator": "mean",
                        "column": "temperature",
                    },
                    {
                        "display_name": "wind_speed",
                        "aggregator": "mean",
                        "column": "wind_speed",
                    },
                    {
                        "display_name": "wind_gusts",
                        "aggregator": "max",
                        "column": "wind_gusts",
                    },
                    {
                        "display_name": "soil_temperature",
                        "aggregator": "mean",
                        "column": "soil_temperature",
                    },
                    {
                        "display_name": "relative_humidity",
                        "aggregator": "mean",
                        "column": "relative_humidity",
                    },
                    {
                        "display_name": "atmospheric_pressure",
                        "aggregator": "mean",
                        "column": "atmospheric_pressure",
                    },
                ],
                "reset_index": True,
            }
            | (params_dict.get("daily_weather") or {}),
            method="call",
        ),
        "persist_weather_summary": Node(
            async_task=persist_df.validate()
            .set_task_instance_id("persist_weather_summary")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filetype": "csv",
                "df": DependsOn("daily_weather"),
                "filename": "mnc_weather_summary",
            }
            | (params_dict.get("persist_weather_summary") or {}),
            method="call",
        ),
        "precipitation_chart": Node(
            async_task=draw_line_chart.validate()
            .set_task_instance_id("precipitation_chart")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "dataframe": DependsOn("daily_weather"),
                "x_column": "date",
                "y_column": "precipitation",
                "category_column": "weather_station",
                "line_kwargs": {
                    "shape": "linear",
                },
                "layout_kwargs": {
                    "title": None,
                    "title_x": 0.01,
                    "title_y": 0.95,
                    "showlegend": True,
                    "fontsize": 20,
                    "fontcolor": "#2c3e50",
                    "plot_bgcolor": "#f5f5f5",
                    "xaxis": {
                        "title": "Date",
                        "showgrid": True,
                        "gridcolor": "#e0e0e0",
                        "gridwidth": 1,
                        "tickformat": "%Y-%m-%d",
                        "tickangle": -45,
                        "rangemode": "auto",
                    },
                    "yaxis": {
                        "title": "Precipitation (mm)",
                        "tickformat": ".1f",
                    },
                    "legend_title": "Weather Station",
                    "hovermode": "x unified",
                },
            }
            | (params_dict.get("precipitation_chart") or {}),
            method="call",
        ),
        "persist_precipitation": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("persist_precipitation")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "text": DependsOn("precipitation_chart"),
                "filename": "precipitation_readings_over_time.html",
            }
            | (params_dict.get("persist_precipitation") or {}),
            method="call",
        ),
        "temperature_chart": Node(
            async_task=draw_line_chart.validate()
            .set_task_instance_id("temperature_chart")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "dataframe": DependsOn("daily_weather"),
                "x_column": "date",
                "y_column": "temperature",
                "category_column": "weather_station",
                "line_kwargs": {
                    "shape": "linear",
                },
                "layout_kwargs": {
                    "title": None,
                    "title_x": 0.01,
                    "title_y": 0.95,
                    "showlegend": True,
                    "fontsize": 20,
                    "fontcolor": "#2c3e50",
                    "plot_bgcolor": "#f5f5f5",
                    "xaxis": {
                        "title": "Date",
                        "tickformat": "%Y-%m-%d",
                        "tickangle": -45,
                        "rangemode": "auto",
                    },
                    "yaxis": {
                        "title": "Average Temperature (°C)",
                        "tickformat": ".1f",
                    },
                    "legend_title": "Weather Station",
                    "hovermode": "x unified",
                },
            }
            | (params_dict.get("temperature_chart") or {}),
            method="call",
        ),
        "persist_temperature": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("persist_temperature")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "text": DependsOn("temperature_chart"),
                "filename": "temperature_readings_over_time.html",
            }
            | (params_dict.get("persist_temperature") or {}),
            method="call",
        ),
        "wind_speed_chart": Node(
            async_task=draw_line_chart.validate()
            .set_task_instance_id("wind_speed_chart")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "dataframe": DependsOn("daily_weather"),
                "x_column": "date",
                "y_column": "wind_speed",
                "category_column": "weather_station",
                "line_kwargs": {
                    "shape": "linear",
                },
                "layout_kwargs": {
                    "title": None,
                    "title_x": 0.01,
                    "title_y": 0.95,
                    "showlegend": True,
                    "fontsize": 20,
                    "fontcolor": "#2c3e50",
                    "plot_bgcolor": "#f5f5f5",
                    "xaxis": {
                        "title": "Date",
                        "tickformat": "%Y-%m-%d",
                        "tickangle": -45,
                        "rangemode": "auto",
                    },
                    "yaxis": {
                        "title": "Average wind speed",
                        "tickformat": ".1f",
                    },
                    "legend_title": "Weather Station",
                    "hovermode": "x unified",
                },
            }
            | (params_dict.get("wind_speed_chart") or {}),
            method="call",
        ),
        "persist_wind_speed": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("persist_wind_speed")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "text": DependsOn("wind_speed_chart"),
                "filename": "wind_speed_readings_over_time.html",
            }
            | (params_dict.get("persist_wind_speed") or {}),
            method="call",
        ),
        "wind_gusts_chart": Node(
            async_task=draw_line_chart.validate()
            .set_task_instance_id("wind_gusts_chart")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "dataframe": DependsOn("daily_weather"),
                "x_column": "date",
                "y_column": "wind_gusts",
                "category_column": "weather_station",
                "line_kwargs": {
                    "shape": "linear",
                },
                "layout_kwargs": {
                    "title": None,
                    "title_x": 0.01,
                    "title_y": 0.95,
                    "showlegend": True,
                    "fontsize": 20,
                    "fontcolor": "#2c3e50",
                    "plot_bgcolor": "#f5f5f5",
                    "xaxis": {
                        "title": "Date",
                        "tickformat": "%Y-%m-%d",
                        "tickangle": -45,
                        "rangemode": "auto",
                    },
                    "yaxis": {
                        "title": "Max wind gusts",
                        "tickformat": ".1f",
                    },
                    "legend_title": "Weather Station",
                    "hovermode": "x unified",
                },
            }
            | (params_dict.get("wind_gusts_chart") or {}),
            method="call",
        ),
        "persist_wind_gusts": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("persist_wind_gusts")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "text": DependsOn("wind_gusts_chart"),
                "filename": "wind_gusts_readings_over_time.html",
            }
            | (params_dict.get("persist_wind_gusts") or {}),
            method="call",
        ),
        "soil_temp_chart": Node(
            async_task=draw_line_chart.validate()
            .set_task_instance_id("soil_temp_chart")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "dataframe": DependsOn("daily_weather"),
                "x_column": "date",
                "y_column": "soil_temperature",
                "category_column": "weather_station",
                "line_kwargs": {
                    "shape": "linear",
                },
                "layout_kwargs": {
                    "title": None,
                    "title_x": 0.01,
                    "title_y": 0.95,
                    "showlegend": True,
                    "fontsize": 20,
                    "fontcolor": "#2c3e50",
                    "plot_bgcolor": "#f5f5f5",
                    "xaxis": {
                        "title": "Date",
                        "tickformat": "%Y-%m-%d",
                        "tickangle": -45,
                        "rangemode": "auto",
                    },
                    "yaxis": {
                        "title": "Average Temperature (°C)",
                        "tickformat": ".1f",
                    },
                    "legend_title": "Weather Station",
                    "hovermode": "x unified",
                },
            }
            | (params_dict.get("soil_temp_chart") or {}),
            method="call",
        ),
        "persist_soil_temp": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("persist_soil_temp")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "text": DependsOn("soil_temp_chart"),
                "filename": "soil_temperature_readings_over_time.html",
            }
            | (params_dict.get("persist_soil_temp") or {}),
            method="call",
        ),
        "rel_humidity_chart": Node(
            async_task=draw_line_chart.validate()
            .set_task_instance_id("rel_humidity_chart")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "dataframe": DependsOn("daily_weather"),
                "x_column": "date",
                "y_column": "relative_humidity",
                "category_column": "weather_station",
                "line_kwargs": {
                    "shape": "linear",
                },
                "layout_kwargs": {
                    "title": None,
                    "title_x": 0.01,
                    "title_y": 0.95,
                    "showlegend": True,
                    "fontsize": 20,
                    "fontcolor": "#2c3e50",
                    "plot_bgcolor": "#f5f5f5",
                    "xaxis": {
                        "title": "Date",
                        "tickformat": "%Y-%m-%d",
                        "tickangle": -45,
                        "rangemode": "auto",
                    },
                    "yaxis": {
                        "title": "Average humidity",
                        "tickformat": ".1f",
                    },
                    "legend_title": "Weather Station",
                    "hovermode": "x unified",
                },
            }
            | (params_dict.get("rel_humidity_chart") or {}),
            method="call",
        ),
        "persist_rel_humidity": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("persist_rel_humidity")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "text": DependsOn("rel_humidity_chart"),
                "filename": "relative_humidity_readings_over_time.html",
            }
            | (params_dict.get("persist_rel_humidity") or {}),
            method="call",
        ),
        "pressure_chart": Node(
            async_task=draw_line_chart.validate()
            .set_task_instance_id("pressure_chart")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "dataframe": DependsOn("daily_weather"),
                "x_column": "date",
                "y_column": "atmospheric_pressure",
                "category_column": "weather_station",
                "line_kwargs": {
                    "shape": "linear",
                },
                "layout_kwargs": {
                    "title": None,
                    "title_x": 0.01,
                    "title_y": 0.95,
                    "showlegend": True,
                    "fontsize": 20,
                    "fontcolor": "#2c3e50",
                    "plot_bgcolor": "#f5f5f5",
                    "xaxis": {
                        "title": "Date",
                        "tickformat": "%Y-%m-%d",
                        "tickangle": -45,
                        "rangemode": "auto",
                    },
                    "yaxis": {
                        "title": "Average pressure",
                        "tickformat": ".1f",
                    },
                    "legend_title": "Weather Station",
                    "hovermode": "x unified",
                },
            }
            | (params_dict.get("pressure_chart") or {}),
            method="call",
        ),
        "persist_pressure": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("persist_pressure")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "text": DependsOn("pressure_chart"),
                "filename": "atmospheric_pressure_readings_over_time.html",
            }
            | (params_dict.get("persist_pressure") or {}),
            method="call",
        ),
        "group_weather_html": Node(
            async_task=groupbykey.validate()
            .set_task_instance_id("group_weather_html")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    all_keyed_iterables_are_skips,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "iterables": [
                    DependsOn("persist_precipitation"),
                    DependsOn("persist_temperature"),
                    DependsOn("persist_wind_speed"),
                    DependsOn("persist_wind_gusts"),
                    DependsOn("persist_soil_temp"),
                    DependsOn("persist_rel_humidity"),
                    DependsOn("persist_pressure"),
                ],
            }
            | (params_dict.get("group_weather_html") or {}),
            method="call",
        ),
        "convert_weather_png": Node(
            async_task=html_to_png.validate()
            .set_task_instance_id("convert_weather_png")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "output_dir": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "html_path": DependsOn("group_weather_html"),
                "config": {
                    "full_page": True,
                    "device_scale_factor": 2.0,
                    "wait_for_timeout": 10,
                    "max_concurrent_pages": 5,
                },
            }
            | (params_dict.get("convert_weather_png") or {}),
            method="call",
        ),
        "mnc_events_dashboard": Node(
            async_task=gather_dashboard.validate()
            .set_task_instance_id("mnc_events_dashboard")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "details": DependsOn("workflow_details"),
                "time_range": DependsOn("time_range"),
                "groupers": DependsOn("groupers"),
            }
            | (params_dict.get("mnc_events_dashboard") or {}),
            method="call",
        ),
    }
    graph = Graph(dependencies=dependencies, nodes=nodes)
    results = graph.execute()
    return results
