# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details
import json
import os

from ecoscope_workflows_core.graph import DependsOn, DependsOnSequence, Graph, Node
from ecoscope_workflows_core.tasks.config import set_workflow_details
from ecoscope_workflows_core.tasks.filter import set_time_range
from ecoscope_workflows_core.tasks.groupby import set_groupers, split_groups
from ecoscope_workflows_core.tasks.io import persist_text, set_er_connection
from ecoscope_workflows_core.tasks.results import (
    create_plot_widget_single_view,
    gather_dashboard,
    merge_widget_views,
)
from ecoscope_workflows_core.tasks.transformation import (
    add_temporal_index,
    extract_column_as_type,
    extract_value_from_json_column,
    map_columns,
)
from ecoscope_workflows_ext_ecoscope.tasks.analysis import summarize_df
from ecoscope_workflows_ext_ecoscope.tasks.io import get_subjectgroup_observations
from ecoscope_workflows_ext_ecoscope.tasks.results import draw_line_chart

from ..params import Params


def main(params: Params):
    params_dict = json.loads(params.model_dump_json(exclude_unset=True))

    dependencies = {
        "workflow_details": [],
        "time_range": [],
        "groupers": [],
        "er_client_name": [],
        "subject_observations": ["er_client_name", "time_range"],
        "extract_precipitation": ["subject_observations"],
        "extract_temperature": ["extract_precipitation"],
        "extract_date": ["extract_temperature"],
        "rename_grouper_columns": ["extract_date"],
        "df_with_temporal_index": ["rename_grouper_columns", "groupers"],
        "split_weather_groups": ["df_with_temporal_index", "groupers"],
        "daily_weather": ["split_weather_groups"],
        "precipitation_chart": ["daily_weather"],
        "persist_precipitation": ["precipitation_chart"],
        "precipitation_chart_widget": ["persist_precipitation"],
        "grouped_precipitation_widget": ["precipitation_chart_widget"],
        "temperature_chart": ["daily_weather"],
        "persist_temperature": ["temperature_chart"],
        "temperature_chart_widget": ["persist_temperature"],
        "grouped_temperature_widget": ["temperature_chart_widget"],
        "weather_dashboard": [
            "workflow_details",
            "grouped_precipitation_widget",
            "grouped_temperature_widget",
            "time_range",
            "groupers",
        ],
    }

    nodes = {
        "workflow_details": Node(
            async_task=set_workflow_details.validate()
            .handle_errors(task_instance_id="workflow_details")
            .set_executor("lithops"),
            partial=(params_dict.get("workflow_details") or {}),
            method="call",
        ),
        "time_range": Node(
            async_task=set_time_range.validate()
            .handle_errors(task_instance_id="time_range")
            .set_executor("lithops"),
            partial={
                "time_format": "%d %b %Y %H:%M:%S %Z",
            }
            | (params_dict.get("time_range") or {}),
            method="call",
        ),
        "groupers": Node(
            async_task=set_groupers.validate()
            .handle_errors(task_instance_id="groupers")
            .set_executor("lithops"),
            partial=(params_dict.get("groupers") or {}),
            method="call",
        ),
        "er_client_name": Node(
            async_task=set_er_connection.validate()
            .handle_errors(task_instance_id="er_client_name")
            .set_executor("lithops"),
            partial=(params_dict.get("er_client_name") or {}),
            method="call",
        ),
        "subject_observations": Node(
            async_task=get_subjectgroup_observations.validate()
            .handle_errors(task_instance_id="subject_observations")
            .set_executor("lithops"),
            partial={
                "client": DependsOn("er_client_name"),
                "time_range": DependsOn("time_range"),
                "raise_on_empty": False,
                "include_details": False,
                "include_subjectsource_details": False,
            }
            | (params_dict.get("subject_observations") or {}),
            method="call",
        ),
        "extract_precipitation": Node(
            async_task=extract_value_from_json_column.validate()
            .handle_errors(task_instance_id="extract_precipitation")
            .set_executor("lithops"),
            partial={
                "df": DependsOn("subject_observations"),
                "column_name": "extra__observation_details",
                "field_name_options": ["precipitation"],
                "output_type": "float",
                "output_column_name": "precipitation",
            }
            | (params_dict.get("extract_precipitation") or {}),
            method="call",
        ),
        "extract_temperature": Node(
            async_task=extract_value_from_json_column.validate()
            .handle_errors(task_instance_id="extract_temperature")
            .set_executor("lithops"),
            partial={
                "df": DependsOn("extract_precipitation"),
                "column_name": "extra__observation_details",
                "field_name_options": ["surface_air_temperature"],
                "output_type": "float",
                "output_column_name": "temperature",
            }
            | (params_dict.get("extract_temperature") or {}),
            method="call",
        ),
        "extract_date": Node(
            async_task=extract_column_as_type.validate()
            .handle_errors(task_instance_id="extract_date")
            .set_executor("lithops"),
            partial={
                "df": DependsOn("extract_temperature"),
                "column_name": "fixtime",
                "output_type": "date",
                "output_column_name": "date",
            }
            | (params_dict.get("extract_date") or {}),
            method="call",
        ),
        "rename_grouper_columns": Node(
            async_task=map_columns.validate()
            .handle_errors(task_instance_id="rename_grouper_columns")
            .set_executor("lithops"),
            partial={
                "df": DependsOn("extract_date"),
                "drop_columns": [],
                "retain_columns": [],
                "rename_columns": {"extra__subject__name": "weather_station"},
            }
            | (params_dict.get("rename_grouper_columns") or {}),
            method="call",
        ),
        "df_with_temporal_index": Node(
            async_task=add_temporal_index.validate()
            .handle_errors(task_instance_id="df_with_temporal_index")
            .set_executor("lithops"),
            partial={
                "df": DependsOn("rename_grouper_columns"),
                "time_col": "fixtime",
                "groupers": DependsOn("groupers"),
            }
            | (params_dict.get("df_with_temporal_index") or {}),
            method="call",
        ),
        "split_weather_groups": Node(
            async_task=split_groups.validate()
            .handle_errors(task_instance_id="split_weather_groups")
            .set_executor("lithops"),
            partial={
                "df": DependsOn("df_with_temporal_index"),
                "groupers": DependsOn("groupers"),
            }
            | (params_dict.get("split_weather_groups") or {}),
            method="call",
        ),
        "daily_weather": Node(
            async_task=summarize_df.validate()
            .handle_errors(task_instance_id="daily_weather")
            .set_executor("lithops"),
            partial={
                "groupby_cols": ["weather_station", "date"],
                "summary_params": [
                    {
                        "display_name": "daily_precipitation",
                        "aggregator": "sum",
                        "column": "precipitation",
                    },
                    {
                        "display_name": "daily_temperature",
                        "aggregator": "mean",
                        "column": "temperature",
                    },
                ],
                "reset_index": True,
            }
            | (params_dict.get("daily_weather") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("split_weather_groups"),
            },
        ),
        "precipitation_chart": Node(
            async_task=draw_line_chart.validate()
            .handle_errors(task_instance_id="precipitation_chart")
            .set_executor("lithops"),
            partial={
                "x_column": "date",
                "y_column": "daily_precipitation",
                "category_column": "weather_station",
                "line_kwargs": {"shape": "linear", "dash": "None", "color": "None"},
                "layout_kwargs": {
                    "title": "Precipitation by Station",
                    "title_x": 0.01,
                    "title_y": 0.95,
                    "showlegend": True,
                    "fontsize": 12,
                    "fontcolor": "#222222",
                    "xaxis": {
                        "title": "Date",
                        "tickformat": "%Y-%m-%d",
                        "tickangle": -45,
                        "rangemode": "auto",
                    },
                    "yaxis": {"title": "Precipitation (mm)", "tickformat": ".1f"},
                    "legend_title": "Weather Station",
                    "hovermode": "x unified",
                },
            }
            | (params_dict.get("precipitation_chart") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["dataframe"],
                "argvalues": DependsOn("daily_weather"),
            },
        ),
        "persist_precipitation": Node(
            async_task=persist_text.validate()
            .handle_errors(task_instance_id="persist_precipitation")
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            }
            | (params_dict.get("persist_precipitation") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["text"],
                "argvalues": DependsOn("precipitation_chart"),
            },
        ),
        "precipitation_chart_widget": Node(
            async_task=create_plot_widget_single_view.validate()
            .handle_errors(task_instance_id="precipitation_chart_widget")
            .set_executor("lithops"),
            partial={
                "title": "Daily Precipitation by Station",
            }
            | (params_dict.get("precipitation_chart_widget") or {}),
            method="map",
            kwargs={
                "argnames": ["view", "data"],
                "argvalues": DependsOn("persist_precipitation"),
            },
        ),
        "grouped_precipitation_widget": Node(
            async_task=merge_widget_views.validate()
            .handle_errors(task_instance_id="grouped_precipitation_widget")
            .set_executor("lithops"),
            partial={
                "widgets": DependsOn("precipitation_chart_widget"),
            }
            | (params_dict.get("grouped_precipitation_widget") or {}),
            method="call",
        ),
        "temperature_chart": Node(
            async_task=draw_line_chart.validate()
            .handle_errors(task_instance_id="temperature_chart")
            .set_executor("lithops"),
            partial={
                "x_column": "date",
                "y_column": "daily_temperature",
                "category_column": "weather_station",
                "line_kwargs": {"shape": "linear", "dash": "None", "color": "None"},
                "layout_kwargs": {
                    "title": "Temperature by Station",
                    "title_x": 0.01,
                    "title_y": 0.95,
                    "showlegend": True,
                    "fontsize": 12,
                    "fontcolor": "#222222",
                    "xaxis": {
                        "title": "Date",
                        "tickformat": "%Y-%m-%d",
                        "tickangle": -45,
                        "rangemode": "auto",
                    },
                    "yaxis": {"title": "Average Temperature (°C)", "tickformat": ".1f"},
                    "legend_title": "Weather Station",
                    "hovermode": "x unified",
                },
            }
            | (params_dict.get("temperature_chart") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["dataframe"],
                "argvalues": DependsOn("daily_weather"),
            },
        ),
        "persist_temperature": Node(
            async_task=persist_text.validate()
            .handle_errors(task_instance_id="persist_temperature")
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            }
            | (params_dict.get("persist_temperature") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["text"],
                "argvalues": DependsOn("temperature_chart"),
            },
        ),
        "temperature_chart_widget": Node(
            async_task=create_plot_widget_single_view.validate()
            .handle_errors(task_instance_id="temperature_chart_widget")
            .set_executor("lithops"),
            partial={
                "title": "Daily Temperature by Station",
            }
            | (params_dict.get("temperature_chart_widget") or {}),
            method="map",
            kwargs={
                "argnames": ["view", "data"],
                "argvalues": DependsOn("persist_temperature"),
            },
        ),
        "grouped_temperature_widget": Node(
            async_task=merge_widget_views.validate()
            .handle_errors(task_instance_id="grouped_temperature_widget")
            .set_executor("lithops"),
            partial={
                "widgets": DependsOn("temperature_chart_widget"),
            }
            | (params_dict.get("grouped_temperature_widget") or {}),
            method="call",
        ),
        "weather_dashboard": Node(
            async_task=gather_dashboard.validate()
            .handle_errors(task_instance_id="weather_dashboard")
            .set_executor("lithops"),
            partial={
                "details": DependsOn("workflow_details"),
                "widgets": DependsOnSequence(
                    [
                        DependsOn("grouped_precipitation_widget"),
                        DependsOn("grouped_temperature_widget"),
                    ],
                ),
                "time_range": DependsOn("time_range"),
                "groupers": DependsOn("groupers"),
            }
            | (params_dict.get("weather_dashboard") or {}),
            method="call",
        ),
    }
    graph = Graph(dependencies=dependencies, nodes=nodes)
    results = graph.execute()
    return results
