# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details

# ruff: noqa: E402

"""WARNING: This file is generated in a testing context and should not be used in production.
Lines specific to the testing context are marked with a test tube emoji (🧪) to indicate
that they would not be included (or would be different) in the production version of this file.
"""

import json
import os
import warnings  # 🧪
from ecoscope_workflows_core.testing import create_task_magicmock  # 🧪


from ecoscope_workflows_core.tasks.config import set_workflow_details
from ecoscope_workflows_core.tasks.filter import set_time_range
from ecoscope_workflows_core.tasks.groupby import set_groupers
from ecoscope_workflows_core.tasks.io import set_er_connection
from ecoscope_workflows_ext_ecoscope.tasks.results import set_base_maps
from ecoscope_workflows_ext_mnc.tasks import download_file_and_persist

get_subjectgroup_observations = create_task_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_ecoscope.tasks.io",  # 🧪
    func_name="get_subjectgroup_observations",  # 🧪
)  # 🧪
from ecoscope_workflows_core.tasks.transformation import extract_value_from_json_column
from ecoscope_workflows_core.tasks.transformation import extract_column_as_type
from ecoscope_workflows_core.tasks.transformation import map_columns
from ecoscope_workflows_core.tasks.transformation import add_temporal_index
from ecoscope_workflows_core.tasks.groupby import split_groups
from ecoscope_workflows_ext_ecoscope.tasks.analysis import summarize_df
from ecoscope_workflows_ext_ecoscope.tasks.results import draw_line_chart
from ecoscope_workflows_core.tasks.io import persist_text
from ecoscope_workflows_core.tasks.results import create_plot_widget_single_view
from ecoscope_workflows_core.tasks.results import merge_widget_views

get_events = create_task_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_ecoscope.tasks.io",  # 🧪
    func_name="get_events",  # 🧪
)  # 🧪
from ecoscope_workflows_ext_mnc.tasks import add_totals_row
from ecoscope_workflows_ext_ecoscope.tasks.io import persist_df
from ecoscope_workflows_ext_mnc.tasks import filter_by_value
from ecoscope_workflows_ext_ecoscope.tasks.transformation import normalize_column

get_patrol_observations = create_task_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_ecoscope.tasks.io",  # 🧪
    func_name="get_patrol_observations",  # 🧪
)  # 🧪
from ecoscope_workflows_ext_ecoscope.tasks.preprocessing import process_relocations
from ecoscope_workflows_ext_ecoscope.tasks.preprocessing import (
    relocations_to_trajectory,
)
from ecoscope_workflows_ext_mnc.tasks import classify_mnc_patrol
from ecoscope_workflows_ext_ecoscope.tasks.transformation import apply_color_map
from ecoscope_workflows_ext_ecoscope.tasks.results import create_polyline_layer
from ecoscope_workflows_core.tasks.skip import any_is_empty_df
from ecoscope_workflows_core.tasks.skip import any_dependency_skipped
from ecoscope_workflows_ext_mnc.tasks import create_view_state_from_gdf
from ecoscope_workflows_ext_mnc.tasks import zip_grouped_by_key
from ecoscope_workflows_ext_ecoscope.tasks.results import draw_ecomap
from ecoscope_workflows_core.tasks.results import create_map_widget_single_view
from ecoscope_workflows_core.tasks.skip import never
from ecoscope_workflows_ext_mnc.tasks import create_patrol_coverage_grid
from ecoscope_workflows_ext_ecoscope.tasks.transformation import apply_classification
from ecoscope_workflows_ext_ecoscope.tasks.results import create_polygon_layer
from ecoscope_workflows_ext_mnc.tasks import html_to_png_pw
from ecoscope_workflows_ext_mnc.tasks import flatten_tuple
from ecoscope_workflows_ext_mnc.tasks import print_output
from ecoscope_workflows_ext_mnc.tasks import create_mnc_context
from ecoscope_workflows_core.tasks.results import gather_dashboard

from ..params import Params


def main(params: Params):
    warnings.warn("This test script should not be used in production!")  # 🧪

    params_dict = json.loads(params.model_dump_json(exclude_unset=True))

    workflow_details = (
        set_workflow_details.validate()
        .handle_errors(task_instance_id="workflow_details")
        .partial(**(params_dict.get("workflow_details") or {}))
        .call()
    )

    time_range = (
        set_time_range.validate()
        .handle_errors(task_instance_id="time_range")
        .partial(
            time_format="%d %b %Y %H:%M:%S %Z", **(params_dict.get("time_range") or {})
        )
        .call()
    )

    groupers = (
        set_groupers.validate()
        .handle_errors(task_instance_id="groupers")
        .partial(**(params_dict.get("groupers") or {}))
        .call()
    )

    er_client_name = (
        set_er_connection.validate()
        .handle_errors(task_instance_id="er_client_name")
        .partial(**(params_dict.get("er_client_name") or {}))
        .call()
    )

    configure_base_maps = (
        set_base_maps.validate()
        .handle_errors(task_instance_id="configure_base_maps")
        .partial(**(params_dict.get("configure_base_maps") or {}))
        .call()
    )

    persist_mnc_tpt = (
        download_file_and_persist.validate()
        .handle_errors(task_instance_id="persist_mnc_tpt")
        .partial(
            url="https://www.dropbox.com/scl/fi/v9vnkxuagrtixs0xdh34p/mara_north_conservancy_report_template_v2.docx?rlkey=c8db8wfezrhu9ekd85ggypf89&st=8xf73hzy&dl=0",
            output_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            overwrite_existing=False,
            **(params_dict.get("persist_mnc_tpt") or {}),
        )
        .call()
    )

    subject_observations = (
        get_subjectgroup_observations.validate()
        .handle_errors(task_instance_id="subject_observations")
        .partial(
            client=er_client_name,
            time_range=time_range,
            raise_on_empty=False,
            include_details=False,
            include_subjectsource_details=False,
            **(params_dict.get("subject_observations") or {}),
        )
        .call()
    )

    extract_precipitation = (
        extract_value_from_json_column.validate()
        .handle_errors(task_instance_id="extract_precipitation")
        .partial(
            df=subject_observations,
            column_name="extra__observation_details",
            field_name_options=["precipitation"],
            output_type="float",
            output_column_name="precipitation",
            **(params_dict.get("extract_precipitation") or {}),
        )
        .call()
    )

    extract_temperature = (
        extract_value_from_json_column.validate()
        .handle_errors(task_instance_id="extract_temperature")
        .partial(
            df=extract_precipitation,
            column_name="extra__observation_details",
            field_name_options=["surface_air_temperature"],
            output_type="float",
            output_column_name="temperature",
            **(params_dict.get("extract_temperature") or {}),
        )
        .call()
    )

    extract_date = (
        extract_column_as_type.validate()
        .handle_errors(task_instance_id="extract_date")
        .partial(
            df=extract_temperature,
            column_name="fixtime",
            output_type="date",
            output_column_name="date",
            **(params_dict.get("extract_date") or {}),
        )
        .call()
    )

    rename_grouper_columns = (
        map_columns.validate()
        .handle_errors(task_instance_id="rename_grouper_columns")
        .partial(
            df=extract_date,
            drop_columns=[],
            retain_columns=[],
            rename_columns={"extra__subject__name": "weather_station"},
            **(params_dict.get("rename_grouper_columns") or {}),
        )
        .call()
    )

    df_with_temporal_index = (
        add_temporal_index.validate()
        .handle_errors(task_instance_id="df_with_temporal_index")
        .partial(
            df=rename_grouper_columns,
            time_col="fixtime",
            groupers=groupers,
            **(params_dict.get("df_with_temporal_index") or {}),
        )
        .call()
    )

    split_weather_groups = (
        split_groups.validate()
        .handle_errors(task_instance_id="split_weather_groups")
        .partial(
            df=df_with_temporal_index,
            groupers=groupers,
            **(params_dict.get("split_weather_groups") or {}),
        )
        .call()
    )

    daily_weather = (
        summarize_df.validate()
        .handle_errors(task_instance_id="daily_weather")
        .partial(
            groupby_cols=["weather_station", "date"],
            summary_params=[
                {
                    "display_name": "daily_precipitation",
                    "aggregator": "sum",
                    "column": "precipitation",
                },
                {
                    "display_name": "daily_temperature",
                    "aggregator": "mean",
                    "column": "temperature",
                },
            ],
            reset_index=True,
            **(params_dict.get("daily_weather") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_weather_groups)
    )

    precipitation_chart = (
        draw_line_chart.validate()
        .handle_errors(task_instance_id="precipitation_chart")
        .partial(
            x_column="date",
            y_column="daily_precipitation",
            category_column="weather_station",
            line_kwargs={"shape": "linear"},
            layout_kwargs={
                "title": "Precipitation by Station",
                "title_x": 0.01,
                "title_y": 0.95,
                "showlegend": True,
                "fontsize": 12,
                "fontcolor": "#222222",
                "xaxis": {
                    "title": "Date",
                    "tickformat": "%Y-%m-%d",
                    "tickangle": -45,
                    "rangemode": "auto",
                },
                "yaxis": {"title": "Precipitation (mm)", "tickformat": ".1f"},
                "legend_title": "Weather Station",
                "hovermode": "x unified",
            },
            **(params_dict.get("precipitation_chart") or {}),
        )
        .mapvalues(argnames=["dataframe"], argvalues=daily_weather)
    )

    persist_precipitation = (
        persist_text.validate()
        .handle_errors(task_instance_id="persist_precipitation")
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            **(params_dict.get("persist_precipitation") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=precipitation_chart)
    )

    precipitation_chart_widget = (
        create_plot_widget_single_view.validate()
        .handle_errors(task_instance_id="precipitation_chart_widget")
        .partial(
            title="Daily Precipitation by Station",
            **(params_dict.get("precipitation_chart_widget") or {}),
        )
        .map(argnames=["view", "data"], argvalues=persist_precipitation)
    )

    grouped_precipitation_widget = (
        merge_widget_views.validate()
        .handle_errors(task_instance_id="grouped_precipitation_widget")
        .partial(
            widgets=precipitation_chart_widget,
            **(params_dict.get("grouped_precipitation_widget") or {}),
        )
        .call()
    )

    temperature_chart = (
        draw_line_chart.validate()
        .handle_errors(task_instance_id="temperature_chart")
        .partial(
            x_column="date",
            y_column="daily_temperature",
            category_column="weather_station",
            line_kwargs={"shape": "linear"},
            layout_kwargs={
                "title": "Temperature by Station",
                "title_x": 0.01,
                "title_y": 0.95,
                "showlegend": True,
                "fontsize": 12,
                "fontcolor": "#222222",
                "xaxis": {
                    "title": "Date",
                    "tickformat": "%Y-%m-%d",
                    "tickangle": -45,
                    "rangemode": "auto",
                },
                "yaxis": {"title": "Average Temperature (°C)", "tickformat": ".1f"},
                "legend_title": "Weather Station",
                "hovermode": "x unified",
            },
            **(params_dict.get("temperature_chart") or {}),
        )
        .mapvalues(argnames=["dataframe"], argvalues=daily_weather)
    )

    persist_temperature = (
        persist_text.validate()
        .handle_errors(task_instance_id="persist_temperature")
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            **(params_dict.get("persist_temperature") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=temperature_chart)
    )

    temperature_chart_widget = (
        create_plot_widget_single_view.validate()
        .handle_errors(task_instance_id="temperature_chart_widget")
        .partial(
            title="Daily Temperature by Station",
            **(params_dict.get("temperature_chart_widget") or {}),
        )
        .map(argnames=["view", "data"], argvalues=persist_temperature)
    )

    grouped_temperature_widget = (
        merge_widget_views.validate()
        .handle_errors(task_instance_id="grouped_temperature_widget")
        .partial(
            widgets=temperature_chart_widget,
            **(params_dict.get("grouped_temperature_widget") or {}),
        )
        .call()
    )

    get_events_data = (
        get_events.validate()
        .handle_errors(task_instance_id="get_events_data")
        .partial(
            client=er_client_name,
            time_range=time_range,
            event_columns=[
                "id",
                "time",
                "event_type",
                "event_category",
                "reported_by",
                "serial_number",
                "geometry",
                "created_at",
                "event_details",
            ],
            raise_on_empty=False,
            include_details=True,
            include_updates=False,
            include_related_events=False,
            **(params_dict.get("get_events_data") or {}),
        )
        .call()
    )

    extract_event_date = (
        extract_column_as_type.validate()
        .handle_errors(task_instance_id="extract_event_date")
        .partial(
            df=get_events_data,
            column_name="created_at",
            output_type="date",
            output_column_name="date",
            **(params_dict.get("extract_event_date") or {}),
        )
        .call()
    )

    events_wtemporal = (
        add_temporal_index.validate()
        .handle_errors(task_instance_id="events_wtemporal")
        .partial(
            df=extract_event_date,
            time_col="created_at",
            groupers=groupers,
            **(params_dict.get("events_wtemporal") or {}),
        )
        .call()
    )

    split_event_groups = (
        split_groups.validate()
        .handle_errors(task_instance_id="split_event_groups")
        .partial(
            df=events_wtemporal,
            groupers=groupers,
            **(params_dict.get("split_event_groups") or {}),
        )
        .call()
    )

    total_events_recorded = (
        summarize_df.validate()
        .handle_errors(task_instance_id="total_events_recorded")
        .partial(
            groupby_cols=["date"],
            summary_params=[
                {
                    "display_name": "no_of_events",
                    "aggregator": "nunique",
                    "column": "id",
                }
            ],
            reset_index=True,
            **(params_dict.get("total_events_recorded") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_event_groups)
    )

    add_total_events_row = (
        add_totals_row.validate()
        .handle_errors(task_instance_id="add_total_events_row")
        .partial(label_col=["date"], **(params_dict.get("add_total_events_row") or {}))
        .mapvalues(argnames=["df"], argvalues=total_events_recorded)
    )

    persist_tevents_df = (
        persist_df.validate()
        .handle_errors(task_instance_id="persist_tevents_df")
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            **(params_dict.get("persist_tevents_df") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=add_total_events_row)
    )

    draw_events_chart = (
        draw_line_chart.validate()
        .handle_errors(task_instance_id="draw_events_chart")
        .partial(
            x_column="date",
            y_column="no_of_events",
            line_kwargs={"shape": "linear"},
            layout_kwargs={
                "title": "Total events recorded",
                "title_x": 0.01,
                "title_y": 0.95,
                "showlegend": False,
                "fontsize": 12,
                "fontcolor": "#222222",
                "xaxis": {
                    "title": "Date",
                    "tickformat": "%Y-%m-%d",
                    "tickangle": -45,
                    "rangemode": "auto",
                },
                "yaxis": {"title": "Count", "tickformat": ".1f"},
                "hovermode": "x unified",
            },
            **(params_dict.get("draw_events_chart") or {}),
        )
        .mapvalues(argnames=["dataframe"], argvalues=total_events_recorded)
    )

    persist_total_events = (
        persist_text.validate()
        .handle_errors(task_instance_id="persist_total_events")
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            **(params_dict.get("persist_total_events") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=draw_events_chart)
    )

    tevents_chart_widget = (
        create_plot_widget_single_view.validate()
        .handle_errors(task_instance_id="tevents_chart_widget")
        .partial(
            title="Total Events", **(params_dict.get("tevents_chart_widget") or {})
        )
        .map(argnames=["view", "data"], argvalues=persist_total_events)
    )

    grouped_tevents_widget = (
        merge_widget_views.validate()
        .handle_errors(task_instance_id="grouped_tevents_widget")
        .partial(
            widgets=tevents_chart_widget,
            **(params_dict.get("grouped_tevents_widget") or {}),
        )
        .call()
    )

    filter_patrol_info_events = (
        filter_by_value.validate()
        .handle_errors(task_instance_id="filter_patrol_info_events")
        .partial(
            column_name="event_type",
            value="patrol_information",
            **(params_dict.get("filter_patrol_info_events") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_event_groups)
    )

    normalize_pi_values = (
        normalize_column.validate()
        .handle_errors(task_instance_id="normalize_pi_values")
        .partial(
            column="event_details", **(params_dict.get("normalize_pi_values") or {})
        )
        .mapvalues(argnames=["df"], argvalues=filter_patrol_info_events)
    )

    patrol_info_summary = (
        summarize_df.validate()
        .handle_errors(task_instance_id="patrol_info_summary")
        .partial(
            groupby_cols=["event_details__patrol_purpose"],
            summary_params=[
                {
                    "display_name": "Number of Patrols",
                    "aggregator": "count",
                    "column": "id",
                }
            ],
            reset_index=True,
            **(params_dict.get("patrol_info_summary") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=normalize_pi_values)
    )

    include_pat_totals = (
        add_totals_row.validate()
        .handle_errors(task_instance_id="include_pat_totals")
        .partial(
            label_col=["event_details__patrol_purpose"],
            **(params_dict.get("include_pat_totals") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=patrol_info_summary)
    )

    persist_patrol_df = (
        persist_df.validate()
        .handle_errors(task_instance_id="persist_patrol_df")
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            **(params_dict.get("persist_patrol_df") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=include_pat_totals)
    )

    patrol_observations = (
        get_patrol_observations.validate()
        .handle_errors(task_instance_id="patrol_observations")
        .partial(
            client=er_client_name,
            time_range=time_range,
            include_patrol_details=True,
            raise_on_empty=True,
            **(params_dict.get("patrol_observations") or {}),
        )
        .call()
    )

    patrol_relocs = (
        process_relocations.validate()
        .handle_errors(task_instance_id="patrol_relocs")
        .partial(
            observations=patrol_observations,
            relocs_columns=[
                "extra__id",
                "extra__created_at",
                "extra__subject_id",
                "geometry",
                "groupby_col",
                "fixtime",
                "junk_status",
                "patrol_id",
                "patrol_title",
                "patrol_serial_number",
                "patrol_start_time",
                "patrol_end_time",
                "patrol_type",
                "patrol_status",
                "patrol_subject",
                "patrol_type__value",
            ],
            filter_point_coords=[
                {"x": 180.0, "y": 90.0},
                {"x": 0.0, "y": 0.0},
                {"x": 1.0, "y": 1.0},
            ],
            **(params_dict.get("patrol_relocs") or {}),
        )
        .call()
    )

    convert_to_trajectories = (
        relocations_to_trajectory.validate()
        .handle_errors(task_instance_id="convert_to_trajectories")
        .partial(
            relocations=patrol_relocs,
            **(params_dict.get("convert_to_trajectories") or {}),
        )
        .call()
    )

    add_temporal_index_to_traj = (
        add_temporal_index.validate()
        .handle_errors(task_instance_id="add_temporal_index_to_traj")
        .partial(
            df=convert_to_trajectories,
            time_col="segment_start",
            groupers=groupers,
            cast_to_datetime=True,
            format="mixed",
            **(params_dict.get("add_temporal_index_to_traj") or {}),
        )
        .call()
    )

    map_patrol_types = (
        classify_mnc_patrol.validate()
        .handle_errors(task_instance_id="map_patrol_types")
        .partial(
            df=add_temporal_index_to_traj,
            patrol_col="extra__patrol_type__value",
            new_col="patrol_cat_types",
            **(params_dict.get("map_patrol_types") or {}),
        )
        .call()
    )

    rename_traj_cols = (
        map_columns.validate()
        .handle_errors(task_instance_id="rename_traj_cols")
        .partial(
            drop_columns=["heading", "extra__created_at", "extra__id"],
            retain_columns=[],
            rename_columns={
                "extra__patrol_start_time": "patrol_start_time",
                "extra__patrol_end_time": "patrol_end_time",
                "extra__patrol_id": "patrol_id",
                "extra__patrol_serial_number": "patrol_serial_number",
                "extra__patrol_status": "patrol_status",
                "extra__patrol_subject": "patrol_subject_name",
                "extra__patrol_title": "patrol_title",
                "extra__patrol_type": "patrol_type_id",
                "extra__patrol_type__value": "patrol_type_value",
                "extra__subject_id": "subject_id",
            },
            df=map_patrol_types,
            **(params_dict.get("rename_traj_cols") or {}),
        )
        .call()
    )

    split_trajectories_by_group = (
        split_groups.validate()
        .handle_errors(task_instance_id="split_trajectories_by_group")
        .partial(
            df=rename_traj_cols,
            groupers=groupers,
            **(params_dict.get("split_trajectories_by_group") or {}),
        )
        .call()
    )

    ranger_patrol_metrics = (
        summarize_df.validate()
        .handle_errors(task_instance_id="ranger_patrol_metrics")
        .partial(
            groupby_cols=["patrol_subject_name"],
            summary_params=[
                {
                    "display_name": "Number of Patrols",
                    "aggregator": "nunique",
                    "column": "patrol_id",
                },
                {
                    "display_name": "Distance (km)",
                    "aggregator": "sum",
                    "column": "dist_meters",
                    "original_unit": "m",
                    "new_unit": "km",
                },
                {
                    "display_name": "Duration (hrs)",
                    "aggregator": "sum",
                    "column": "timespan_seconds",
                    "original_unit": "s",
                    "new_unit": "h",
                },
            ],
            reset_index=True,
            **(params_dict.get("ranger_patrol_metrics") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_trajectories_by_group)
    )

    persist_total_df = (
        persist_df.validate()
        .handle_errors(task_instance_id="persist_total_df")
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            **(params_dict.get("persist_total_df") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=ranger_patrol_metrics)
    )

    filter_foot_patrols = (
        filter_by_value.validate()
        .handle_errors(task_instance_id="filter_foot_patrols")
        .partial(
            column_name="patrol_cat_types",
            value="Foot",
            **(params_dict.get("filter_foot_patrols") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_trajectories_by_group)
    )

    foot_patrol_metrics = (
        summarize_df.validate()
        .handle_errors(task_instance_id="foot_patrol_metrics")
        .partial(
            groupby_cols=["patrol_cat_types"],
            summary_params=[
                {
                    "display_name": "no_of_patrols",
                    "aggregator": "nunique",
                    "column": "patrol_id",
                },
                {
                    "display_name": "distance_km",
                    "aggregator": "sum",
                    "column": "dist_meters",
                    "original_unit": "m",
                    "new_unit": "km",
                },
                {
                    "display_name": "duration_hrs",
                    "aggregator": "sum",
                    "column": "timespan_seconds",
                    "original_unit": "s",
                    "new_unit": "h",
                },
            ],
            reset_index=True,
            **(params_dict.get("foot_patrol_metrics") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=filter_foot_patrols)
    )

    persist_fps_df = (
        persist_df.validate()
        .handle_errors(task_instance_id="persist_fps_df")
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            **(params_dict.get("persist_fps_df") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=foot_patrol_metrics)
    )

    apply_footp_colormap = (
        apply_color_map.validate()
        .handle_errors(task_instance_id="apply_footp_colormap")
        .partial(
            input_column_name="patrol_type_value",
            output_column_name="patrol_colormap",
            colormap="coolwarm",
            **(params_dict.get("apply_footp_colormap") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=filter_foot_patrols)
    )

    generate_footp_layers = (
        create_polyline_layer.validate()
        .handle_errors(task_instance_id="generate_footp_layers")
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            layer_style={"color_column": "patrol_colormap"},
            legend={
                "label_column": "patrol_type_value",
                "color_column": "patrol_colormap",
            },
            tooltip_columns=[
                "patrol_subject_name",
                "patrol_start_time",
                "patrol_end_time",
                "patrol_title",
                "patrol_type_value",
                "segment_start",
                "dist_meters",
                "timespan_seconds",
            ],
            **(params_dict.get("generate_footp_layers") or {}),
        )
        .mapvalues(argnames=["geodataframe"], argvalues=apply_footp_colormap)
    )

    zoom_footp_traj_view = (
        create_view_state_from_gdf.validate()
        .handle_errors(task_instance_id="zoom_footp_traj_view")
        .partial(pitch=0, bearing=0, **(params_dict.get("zoom_footp_traj_view") or {}))
        .mapvalues(argnames=["gdf"], argvalues=apply_footp_colormap)
    )

    zip_footp_zoom_values = (
        zip_grouped_by_key.validate()
        .handle_errors(task_instance_id="zip_footp_zoom_values")
        .partial(
            left=generate_footp_layers,
            right=zoom_footp_traj_view,
            **(params_dict.get("zip_footp_zoom_values") or {}),
        )
        .call()
    )

    draw_footp_ecomap = (
        draw_ecomap.validate()
        .handle_errors(task_instance_id="draw_footp_ecomap")
        .partial(
            tile_layers=configure_base_maps,
            north_arrow_style={"placement": "top-left"},
            legend_style={"placement": "bottom-right", "title": "Patrol Types"},
            static=False,
            title=None,
            max_zoom=20,
            **(params_dict.get("draw_footp_ecomap") or {}),
        )
        .mapvalues(
            argnames=["geo_layers", "view_state"], argvalues=zip_footp_zoom_values
        )
    )

    persist_footp_ecomap_urls = (
        persist_text.validate()
        .handle_errors(task_instance_id="persist_footp_ecomap_urls")
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            **(params_dict.get("persist_footp_ecomap_urls") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=draw_footp_ecomap)
    )

    create_footp_widgets = (
        create_map_widget_single_view.validate()
        .handle_errors(task_instance_id="create_footp_widgets")
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(title="Foot Patrol", **(params_dict.get("create_footp_widgets") or {}))
        .map(argnames=["view", "data"], argvalues=persist_footp_ecomap_urls)
    )

    merge_footp_widgets = (
        merge_widget_views.validate()
        .handle_errors(task_instance_id="merge_footp_widgets")
        .partial(
            widgets=create_footp_widgets,
            **(params_dict.get("merge_footp_widgets") or {}),
        )
        .call()
    )

    filter_vehicle_patrols = (
        filter_by_value.validate()
        .handle_errors(task_instance_id="filter_vehicle_patrols")
        .partial(
            column_name="patrol_cat_types",
            value="Vehicle",
            **(params_dict.get("filter_vehicle_patrols") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_trajectories_by_group)
    )

    vh_patrol_metrics = (
        summarize_df.validate()
        .handle_errors(task_instance_id="vh_patrol_metrics")
        .partial(
            groupby_cols=["patrol_cat_types"],
            summary_params=[
                {
                    "display_name": "no_of_patrols",
                    "aggregator": "nunique",
                    "column": "patrol_id",
                },
                {
                    "display_name": "distance_km",
                    "aggregator": "sum",
                    "column": "dist_meters",
                    "original_unit": "m",
                    "new_unit": "km",
                },
                {
                    "display_name": "duration_hrs",
                    "aggregator": "sum",
                    "column": "timespan_seconds",
                    "original_unit": "s",
                    "new_unit": "h",
                },
                {
                    "display_name": "average_speed",
                    "aggregator": "mean",
                    "column": "speed_kmhr",
                },
            ],
            reset_index=True,
            **(params_dict.get("vh_patrol_metrics") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=filter_vehicle_patrols)
    )

    persist_vh_df = (
        persist_df.validate()
        .handle_errors(task_instance_id="persist_vh_df")
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            **(params_dict.get("persist_vh_df") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=vh_patrol_metrics)
    )

    apply_vhp_colormap = (
        apply_color_map.validate()
        .handle_errors(task_instance_id="apply_vhp_colormap")
        .partial(
            input_column_name="patrol_type_value",
            output_column_name="patrol_colormap",
            colormap="coolwarm",
            **(params_dict.get("apply_vhp_colormap") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=filter_vehicle_patrols)
    )

    generate_vhp_layers = (
        create_polyline_layer.validate()
        .handle_errors(task_instance_id="generate_vhp_layers")
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            layer_style={"color_column": "patrol_colormap"},
            legend={
                "label_column": "patrol_type_value",
                "color_column": "patrol_colormap",
            },
            tooltip_columns=[
                "patrol_subject_name",
                "patrol_start_time",
                "patrol_end_time",
                "patrol_title",
                "patrol_type_value",
                "segment_start",
                "dist_meters",
                "timespan_seconds",
            ],
            **(params_dict.get("generate_vhp_layers") or {}),
        )
        .mapvalues(argnames=["geodataframe"], argvalues=apply_vhp_colormap)
    )

    zoom_vhp_traj_view = (
        create_view_state_from_gdf.validate()
        .handle_errors(task_instance_id="zoom_vhp_traj_view")
        .partial(pitch=0, bearing=0, **(params_dict.get("zoom_vhp_traj_view") or {}))
        .mapvalues(argnames=["gdf"], argvalues=apply_vhp_colormap)
    )

    zip_vhp_zoom_values = (
        zip_grouped_by_key.validate()
        .handle_errors(task_instance_id="zip_vhp_zoom_values")
        .partial(
            left=generate_vhp_layers,
            right=zoom_vhp_traj_view,
            **(params_dict.get("zip_vhp_zoom_values") or {}),
        )
        .call()
    )

    draw_vhp_ecomap = (
        draw_ecomap.validate()
        .handle_errors(task_instance_id="draw_vhp_ecomap")
        .partial(
            tile_layers=configure_base_maps,
            north_arrow_style={"placement": "top-left"},
            legend_style={"placement": "bottom-right", "title": "Patrol Types"},
            static=False,
            title=None,
            max_zoom=20,
            **(params_dict.get("draw_vhp_ecomap") or {}),
        )
        .mapvalues(argnames=["geo_layers", "view_state"], argvalues=zip_vhp_zoom_values)
    )

    persist_vhp_ecomap_urls = (
        persist_text.validate()
        .handle_errors(task_instance_id="persist_vhp_ecomap_urls")
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            **(params_dict.get("persist_vhp_ecomap_urls") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=draw_vhp_ecomap)
    )

    create_vhp_widgets = (
        create_map_widget_single_view.validate()
        .handle_errors(task_instance_id="create_vhp_widgets")
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Vehicle Patrol", **(params_dict.get("create_vhp_widgets") or {})
        )
        .map(argnames=["view", "data"], argvalues=persist_vhp_ecomap_urls)
    )

    merge_vhp_widgets = (
        merge_widget_views.validate()
        .handle_errors(task_instance_id="merge_vhp_widgets")
        .partial(
            widgets=create_vhp_widgets, **(params_dict.get("merge_vhp_widgets") or {})
        )
        .call()
    )

    filter_motor_patrols = (
        filter_by_value.validate()
        .handle_errors(task_instance_id="filter_motor_patrols")
        .partial(
            column_name="patrol_cat_types",
            value="Motorcycle",
            **(params_dict.get("filter_motor_patrols") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_trajectories_by_group)
    )

    mb_patrol_metrics = (
        summarize_df.validate()
        .handle_errors(task_instance_id="mb_patrol_metrics")
        .partial(
            groupby_cols=["patrol_cat_types"],
            summary_params=[
                {
                    "display_name": "no_of_patrols",
                    "aggregator": "nunique",
                    "column": "patrol_id",
                },
                {
                    "display_name": "distance_km",
                    "aggregator": "sum",
                    "column": "dist_meters",
                    "original_unit": "m",
                    "new_unit": "km",
                },
                {
                    "display_name": "duration_hrs",
                    "aggregator": "sum",
                    "column": "timespan_seconds",
                    "original_unit": "s",
                    "new_unit": "h",
                },
                {
                    "display_name": "average_speed",
                    "aggregator": "mean",
                    "column": "speed_kmhr",
                },
            ],
            reset_index=True,
            **(params_dict.get("mb_patrol_metrics") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=filter_motor_patrols)
    )

    persist_mb_df = (
        persist_df.validate()
        .handle_errors(task_instance_id="persist_mb_df")
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            **(params_dict.get("persist_mb_df") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=mb_patrol_metrics)
    )

    apply_mocp_colormap = (
        apply_color_map.validate()
        .handle_errors(task_instance_id="apply_mocp_colormap")
        .partial(
            input_column_name="patrol_type_value",
            output_column_name="patrol_colormap",
            colormap="coolwarm",
            **(params_dict.get("apply_mocp_colormap") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=filter_motor_patrols)
    )

    generate_mocp_layers = (
        create_polyline_layer.validate()
        .handle_errors(task_instance_id="generate_mocp_layers")
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            layer_style={"color_column": "patrol_colormap"},
            legend={
                "label_column": "patrol_type_value",
                "color_column": "patrol_colormap",
            },
            tooltip_columns=[
                "patrol_subject_name",
                "patrol_start_time",
                "patrol_end_time",
                "patrol_title",
                "patrol_type_value",
                "segment_start",
                "dist_meters",
                "timespan_seconds",
            ],
            **(params_dict.get("generate_mocp_layers") or {}),
        )
        .mapvalues(argnames=["geodataframe"], argvalues=apply_mocp_colormap)
    )

    zoom_mocp_traj_view = (
        create_view_state_from_gdf.validate()
        .handle_errors(task_instance_id="zoom_mocp_traj_view")
        .partial(pitch=0, bearing=0, **(params_dict.get("zoom_mocp_traj_view") or {}))
        .mapvalues(argnames=["gdf"], argvalues=apply_mocp_colormap)
    )

    zip_mocp_zoom_values = (
        zip_grouped_by_key.validate()
        .handle_errors(task_instance_id="zip_mocp_zoom_values")
        .partial(
            left=generate_mocp_layers,
            right=zoom_mocp_traj_view,
            **(params_dict.get("zip_mocp_zoom_values") or {}),
        )
        .call()
    )

    draw_mocp_ecomap = (
        draw_ecomap.validate()
        .handle_errors(task_instance_id="draw_mocp_ecomap")
        .partial(
            tile_layers=configure_base_maps,
            north_arrow_style={"placement": "top-left"},
            legend_style={"placement": "bottom-right", "title": "Patrol Types"},
            static=False,
            title=None,
            max_zoom=20,
            **(params_dict.get("draw_mocp_ecomap") or {}),
        )
        .mapvalues(
            argnames=["geo_layers", "view_state"], argvalues=zip_mocp_zoom_values
        )
    )

    persist_mocp_ecomap_urls = (
        persist_text.validate()
        .handle_errors(task_instance_id="persist_mocp_ecomap_urls")
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            **(params_dict.get("persist_mocp_ecomap_urls") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=draw_mocp_ecomap)
    )

    create_mocp_widgets = (
        create_map_widget_single_view.validate()
        .handle_errors(task_instance_id="create_mocp_widgets")
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Motorbike Patrol", **(params_dict.get("create_mocp_widgets") or {})
        )
        .map(argnames=["view", "data"], argvalues=persist_mocp_ecomap_urls)
    )

    merge_mocp_widgets = (
        merge_widget_views.validate()
        .handle_errors(task_instance_id="merge_mocp_widgets")
        .partial(
            widgets=create_mocp_widgets, **(params_dict.get("merge_mocp_widgets") or {})
        )
        .call()
    )

    patrol_grid_visits = (
        create_patrol_coverage_grid.validate()
        .handle_errors(task_instance_id="patrol_grid_visits")
        .partial(grid_cell_size=1000, **(params_dict.get("patrol_grid_visits") or {}))
        .mapvalues(argnames=["trajs"], argvalues=split_trajectories_by_group)
    )

    apply_classification_grid = (
        apply_classification.validate()
        .handle_errors(task_instance_id="apply_classification_grid")
        .partial(
            input_column_name="unique_patrol_count",
            output_column_name="density_bins",
            **(params_dict.get("apply_classification_grid") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=patrol_grid_visits)
    )

    apply_grid_colormap = (
        apply_color_map.validate()
        .handle_errors(task_instance_id="apply_grid_colormap")
        .partial(
            input_column_name="density_bins",
            colormap="RdYlGn",
            output_column_name="density_colors",
            **(params_dict.get("apply_grid_colormap") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=apply_classification_grid)
    )

    generate_grid_layers = (
        create_polygon_layer.validate()
        .handle_errors(task_instance_id="generate_grid_layers")
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            layer_style={
                "fill_color_column": "density_colors",
                "opacity": 0.25,
                "get_line_width": 1,
                "stroked": True,
            },
            legend={"label_column": "density_bins", "color_column": "density_colors"},
            tooltip_columns=["density_bins", "density_colors"],
            **(params_dict.get("generate_grid_layers") or {}),
        )
        .mapvalues(argnames=["geodataframe"], argvalues=apply_grid_colormap)
    )

    zoom_grid_view = (
        create_view_state_from_gdf.validate()
        .handle_errors(task_instance_id="zoom_grid_view")
        .partial(pitch=0, bearing=0, **(params_dict.get("zoom_grid_view") or {}))
        .mapvalues(argnames=["gdf"], argvalues=apply_grid_colormap)
    )

    zip_grid_zoom_values = (
        zip_grouped_by_key.validate()
        .handle_errors(task_instance_id="zip_grid_zoom_values")
        .partial(
            left=generate_grid_layers,
            right=zoom_grid_view,
            **(params_dict.get("zip_grid_zoom_values") or {}),
        )
        .call()
    )

    draw_grid_ecomap = (
        draw_ecomap.validate()
        .handle_errors(task_instance_id="draw_grid_ecomap")
        .partial(
            tile_layers=configure_base_maps,
            north_arrow_style={"placement": "top-left"},
            legend_style={"placement": "bottom-right", "title": "Grid visits"},
            static=False,
            title=None,
            max_zoom=20,
            **(params_dict.get("draw_grid_ecomap") or {}),
        )
        .mapvalues(
            argnames=["geo_layers", "view_state"], argvalues=zip_grid_zoom_values
        )
    )

    persist_grid_ecomap_urls = (
        persist_text.validate()
        .handle_errors(task_instance_id="persist_grid_ecomap_urls")
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            **(params_dict.get("persist_grid_ecomap_urls") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=draw_grid_ecomap)
    )

    create_grid_widgets = (
        create_map_widget_single_view.validate()
        .handle_errors(task_instance_id="create_grid_widgets")
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Patrol Grid Visits", **(params_dict.get("create_grid_widgets") or {})
        )
        .map(argnames=["view", "data"], argvalues=persist_grid_ecomap_urls)
    )

    merge_grid_widgets = (
        merge_widget_views.validate()
        .handle_errors(task_instance_id="merge_grid_widgets")
        .partial(
            widgets=create_grid_widgets, **(params_dict.get("merge_grid_widgets") or {})
        )
        .call()
    )

    convert_footp_html_to_png = (
        html_to_png_pw.validate()
        .handle_errors(task_instance_id="convert_footp_html_to_png")
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={"wait_for_timeout": 20000},
            **(params_dict.get("convert_footp_html_to_png") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_footp_ecomap_urls)
    )

    convert_vhp_html_to_png = (
        html_to_png_pw.validate()
        .handle_errors(task_instance_id="convert_vhp_html_to_png")
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={"wait_for_timeout": 20000},
            **(params_dict.get("convert_vhp_html_to_png") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_vhp_ecomap_urls)
    )

    convert_mbp_html_to_png = (
        html_to_png_pw.validate()
        .handle_errors(task_instance_id="convert_mbp_html_to_png")
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={"wait_for_timeout": 20000},
            **(params_dict.get("convert_mbp_html_to_png") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_mocp_ecomap_urls)
    )

    convert_temp_html_to_png = (
        html_to_png_pw.validate()
        .handle_errors(task_instance_id="convert_temp_html_to_png")
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={"wait_for_timeout": 200},
            **(params_dict.get("convert_temp_html_to_png") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_temperature)
    )

    convert_prec_html_to_png = (
        html_to_png_pw.validate()
        .handle_errors(task_instance_id="convert_prec_html_to_png")
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={"wait_for_timeout": 200},
            **(params_dict.get("convert_prec_html_to_png") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_precipitation)
    )

    convert_tev_html_to_png = (
        html_to_png_pw.validate()
        .handle_errors(task_instance_id="convert_tev_html_to_png")
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={"wait_for_timeout": 200},
            **(params_dict.get("convert_tev_html_to_png") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_total_events)
    )

    convert_patgr_html_to_png = (
        html_to_png_pw.validate()
        .handle_errors(task_instance_id="convert_patgr_html_to_png")
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={"wait_for_timeout": 20000},
            **(params_dict.get("convert_patgr_html_to_png") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_grid_ecomap_urls)
    )

    zip_tevents_ps = (
        zip_grouped_by_key.validate()
        .handle_errors(task_instance_id="zip_tevents_ps")
        .partial(
            left=persist_tevents_df,
            right=persist_fps_df,
            **(params_dict.get("zip_tevents_ps") or {}),
        )
        .call()
    )

    zip_tps_vh = (
        zip_grouped_by_key.validate()
        .handle_errors(task_instance_id="zip_tps_vh")
        .partial(
            left=zip_tevents_ps,
            right=persist_vh_df,
            **(params_dict.get("zip_tps_vh") or {}),
        )
        .call()
    )

    zip_tpsvhmp = (
        zip_grouped_by_key.validate()
        .handle_errors(task_instance_id="zip_tpsvhmp")
        .partial(
            left=zip_tps_vh,
            right=persist_mb_df,
            **(params_dict.get("zip_tpsvhmp") or {}),
        )
        .call()
    )

    zip_patrol_purpose = (
        zip_grouped_by_key.validate()
        .handle_errors(task_instance_id="zip_patrol_purpose")
        .partial(
            left=zip_tpsvhmp,
            right=persist_patrol_df,
            **(params_dict.get("zip_patrol_purpose") or {}),
        )
        .call()
    )

    zip_ranger_metrics = (
        zip_grouped_by_key.validate()
        .handle_errors(task_instance_id="zip_ranger_metrics")
        .partial(
            left=zip_patrol_purpose,
            right=persist_total_df,
            **(params_dict.get("zip_ranger_metrics") or {}),
        )
        .call()
    )

    zip_temp_urls = (
        zip_grouped_by_key.validate()
        .handle_errors(task_instance_id="zip_temp_urls")
        .partial(
            left=zip_ranger_metrics,
            right=convert_temp_html_to_png,
            **(params_dict.get("zip_temp_urls") or {}),
        )
        .call()
    )

    zip_precip_urls = (
        zip_grouped_by_key.validate()
        .handle_errors(task_instance_id="zip_precip_urls")
        .partial(
            left=zip_temp_urls,
            right=convert_prec_html_to_png,
            **(params_dict.get("zip_precip_urls") or {}),
        )
        .call()
    )

    zip_events_urls = (
        zip_grouped_by_key.validate()
        .handle_errors(task_instance_id="zip_events_urls")
        .partial(
            left=zip_precip_urls,
            right=convert_tev_html_to_png,
            **(params_dict.get("zip_events_urls") or {}),
        )
        .call()
    )

    zip_footp_urls = (
        zip_grouped_by_key.validate()
        .handle_errors(task_instance_id="zip_footp_urls")
        .partial(
            left=zip_events_urls,
            right=convert_footp_html_to_png,
            **(params_dict.get("zip_footp_urls") or {}),
        )
        .call()
    )

    zip_vhp_urls = (
        zip_grouped_by_key.validate()
        .handle_errors(task_instance_id="zip_vhp_urls")
        .partial(
            left=zip_footp_urls,
            right=convert_vhp_html_to_png,
            **(params_dict.get("zip_vhp_urls") or {}),
        )
        .call()
    )

    zip_mb_urls = (
        zip_grouped_by_key.validate()
        .handle_errors(task_instance_id="zip_mb_urls")
        .partial(
            left=zip_vhp_urls,
            right=convert_mbp_html_to_png,
            **(params_dict.get("zip_mb_urls") or {}),
        )
        .call()
    )

    zip_patrolcov_urls = (
        zip_grouped_by_key.validate()
        .handle_errors(task_instance_id="zip_patrolcov_urls")
        .partial(
            left=zip_mb_urls,
            right=convert_patgr_html_to_png,
            **(params_dict.get("zip_patrolcov_urls") or {}),
        )
        .call()
    )

    flatten_zipped_context = (
        flatten_tuple.validate()
        .handle_errors(task_instance_id="flatten_zipped_context")
        .partial(**(params_dict.get("flatten_zipped_context") or {}))
        .mapvalues(argnames=["nested"], argvalues=zip_patrolcov_urls)
    )

    print_flattened_outputs = (
        print_output.validate()
        .handle_errors(task_instance_id="print_flattened_outputs")
        .partial(**(params_dict.get("print_flattened_outputs") or {}))
        .mapvalues(argnames=["value"], argvalues=flatten_zipped_context)
    )

    mnc_context = (
        create_mnc_context.validate()
        .handle_errors(task_instance_id="mnc_context")
        .partial(
            template_path=persist_mnc_tpt,
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            time_period=time_range,
            **(params_dict.get("mnc_context") or {}),
        )
        .mapvalues(
            argnames=[
                "total_events_df",
                "foot_patrols_summary_df",
                "vehicle_patrols_summary_df",
                "motor_patrols_summary_df",
                "patrol_purpose_summary_df",
                "patrol_effort_summary_df",
                "temperature_chart",
                "precipitation_chart",
                "total_events_chart",
                "foot_patrols_map",
                "vehicle_patrols_map",
                "motorbike_patrols_map",
                "patrols_coverage_map",
            ],
            argvalues=flatten_zipped_context,
        )
    )

    weather_dashboard = (
        gather_dashboard.validate()
        .handle_errors(task_instance_id="weather_dashboard")
        .partial(
            details=workflow_details,
            widgets=[
                grouped_precipitation_widget,
                grouped_temperature_widget,
                grouped_tevents_widget,
                merge_footp_widgets,
                merge_vhp_widgets,
                merge_mocp_widgets,
                merge_grid_widgets,
            ],
            time_range=time_range,
            groupers=groupers,
            **(params_dict.get("weather_dashboard") or {}),
        )
        .call()
    )

    return weather_dashboard
