# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details
import json
import os

from ecoscope_workflows_core.graph import DependsOn, DependsOnSequence, Graph, Node
from ecoscope_workflows_core.tasks.config import set_workflow_details
from ecoscope_workflows_core.tasks.filter import set_time_range
from ecoscope_workflows_core.tasks.groupby import set_groupers, split_groups
from ecoscope_workflows_core.tasks.io import persist_text, set_er_connection
from ecoscope_workflows_core.tasks.results import (
    create_map_widget_single_view,
    create_plot_widget_single_view,
    gather_dashboard,
    merge_widget_views,
)
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped,
    any_is_empty_df,
    never,
)
from ecoscope_workflows_core.tasks.transformation import (
    add_temporal_index,
    extract_column_as_type,
    extract_value_from_json_column,
    map_columns,
)
from ecoscope_workflows_ext_ecoscope.tasks.analysis import summarize_df
from ecoscope_workflows_ext_ecoscope.tasks.io import (
    get_events,
    get_patrol_observations,
    get_subjectgroup_observations,
    persist_df,
)
from ecoscope_workflows_ext_ecoscope.tasks.preprocessing import (
    process_relocations,
    relocations_to_trajectory,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import (
    create_polyline_layer,
    draw_ecomap,
    draw_line_chart,
    set_base_maps,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    apply_classification,
    apply_color_map,
    normalize_column,
)
from ecoscope_workflows_ext_mnc.tasks import (
    add_totals_row,
    classify_mnc_patrol,
    create_patrol_coverage_grid,
    create_view_state_from_gdf,
    filter_by_value,
    zip_grouped_by_key,
)

from ..params import Params


def main(params: Params):
    params_dict = json.loads(params.model_dump_json(exclude_unset=True))

    dependencies = {
        "workflow_details": [],
        "time_range": [],
        "groupers": [],
        "er_client_name": [],
        "configure_base_maps": [],
        "subject_observations": ["er_client_name", "time_range"],
        "extract_precipitation": ["subject_observations"],
        "extract_temperature": ["extract_precipitation"],
        "extract_date": ["extract_temperature"],
        "rename_grouper_columns": ["extract_date"],
        "df_with_temporal_index": ["rename_grouper_columns", "groupers"],
        "split_weather_groups": ["df_with_temporal_index", "groupers"],
        "daily_weather": ["split_weather_groups"],
        "precipitation_chart": ["daily_weather"],
        "persist_precipitation": ["precipitation_chart"],
        "precipitation_chart_widget": ["persist_precipitation"],
        "grouped_precipitation_widget": ["precipitation_chart_widget"],
        "temperature_chart": ["daily_weather"],
        "persist_temperature": ["temperature_chart"],
        "temperature_chart_widget": ["persist_temperature"],
        "grouped_temperature_widget": ["temperature_chart_widget"],
        "get_events_data": ["er_client_name", "time_range"],
        "extract_event_date": ["get_events_data"],
        "events_wtemporal": ["extract_event_date", "groupers"],
        "split_event_groups": ["events_wtemporal", "groupers"],
        "total_events_recorded": ["split_event_groups"],
        "persist_tevents_df": ["total_events_recorded"],
        "draw_events_chart": ["total_events_recorded"],
        "persist_total_events": ["draw_events_chart"],
        "tevents_chart_widget": ["persist_total_events"],
        "grouped_tevents_widget": ["tevents_chart_widget"],
        "filter_patrol_info_events": ["split_event_groups"],
        "normalize_pi_values": ["filter_patrol_info_events"],
        "rename_patrolinf_cols": ["normalize_pi_values"],
        "patrol_info_summary": ["rename_patrolinf_cols"],
        "include_pat_totals": ["patrol_info_summary"],
        "persist_patrol_df": ["include_pat_totals"],
        "patrol_observations": ["er_client_name", "time_range"],
        "patrol_relocs": ["patrol_observations"],
        "convert_to_trajectories": ["patrol_relocs"],
        "add_temporal_index_to_traj": ["convert_to_trajectories", "groupers"],
        "map_patrol_types": ["add_temporal_index_to_traj"],
        "rename_traj_cols": ["map_patrol_types"],
        "split_trajectories_by_group": ["rename_traj_cols", "groupers"],
        "filter_foot_patrols": ["split_trajectories_by_group"],
        "apply_footp_colormap": ["filter_foot_patrols"],
        "generate_footp_layers": ["apply_footp_colormap"],
        "zoom_footp_traj_view": ["apply_footp_colormap"],
        "zip_footp_zoom_values": ["generate_footp_layers", "zoom_footp_traj_view"],
        "draw_footp_ecomap": ["configure_base_maps", "zip_footp_zoom_values"],
        "persist_footp_ecomap_urls": ["draw_footp_ecomap"],
        "create_footp_widgets": ["persist_footp_ecomap_urls"],
        "merge_footp_widgets": ["create_footp_widgets"],
        "filter_vehicle_patrols": ["split_trajectories_by_group"],
        "apply_vhp_colormap": ["filter_vehicle_patrols"],
        "generate_vhp_layers": ["apply_vhp_colormap"],
        "zoom_vhp_traj_view": ["apply_vhp_colormap"],
        "zip_vhp_zoom_values": ["generate_vhp_layers", "zoom_vhp_traj_view"],
        "draw_vhp_ecomap": ["configure_base_maps", "zip_vhp_zoom_values"],
        "persist_vhp_ecomap_urls": ["draw_vhp_ecomap"],
        "create_vhp_widgets": ["persist_vhp_ecomap_urls"],
        "merge_vhp_widgets": ["create_vhp_widgets"],
        "filter_motor_patrols": ["split_trajectories_by_group"],
        "apply_mocp_colormap": ["filter_motor_patrols"],
        "generate_mocp_layers": ["apply_mocp_colormap"],
        "zoom_mocp_traj_view": ["apply_mocp_colormap"],
        "zip_mocp_zoom_values": ["generate_mocp_layers", "zoom_mocp_traj_view"],
        "draw_mocp_ecomap": ["configure_base_maps", "zip_mocp_zoom_values"],
        "persist_mocp_ecomap_urls": ["draw_mocp_ecomap"],
        "create_mocp_widgets": ["persist_mocp_ecomap_urls"],
        "merge_mocp_widgets": ["create_mocp_widgets"],
        "patrol_grid_visits": ["split_trajectories_by_group"],
        "apply_classification_grid": ["patrol_grid_visits"],
        "apply_grid_colormap": ["apply_classification_grid"],
        "ranger_patrol_metrics": ["split_trajectories_by_group"],
        "persist_total_df": ["ranger_patrol_metrics"],
        "weather_dashboard": [
            "workflow_details",
            "grouped_precipitation_widget",
            "grouped_temperature_widget",
            "grouped_tevents_widget",
            "merge_footp_widgets",
            "merge_vhp_widgets",
            "merge_mocp_widgets",
            "time_range",
            "groupers",
        ],
    }

    nodes = {
        "workflow_details": Node(
            async_task=set_workflow_details.validate()
            .handle_errors(task_instance_id="workflow_details")
            .set_executor("lithops"),
            partial=(params_dict.get("workflow_details") or {}),
            method="call",
        ),
        "time_range": Node(
            async_task=set_time_range.validate()
            .handle_errors(task_instance_id="time_range")
            .set_executor("lithops"),
            partial={
                "time_format": "%d %b %Y %H:%M:%S %Z",
            }
            | (params_dict.get("time_range") or {}),
            method="call",
        ),
        "groupers": Node(
            async_task=set_groupers.validate()
            .handle_errors(task_instance_id="groupers")
            .set_executor("lithops"),
            partial=(params_dict.get("groupers") or {}),
            method="call",
        ),
        "er_client_name": Node(
            async_task=set_er_connection.validate()
            .handle_errors(task_instance_id="er_client_name")
            .set_executor("lithops"),
            partial=(params_dict.get("er_client_name") or {}),
            method="call",
        ),
        "configure_base_maps": Node(
            async_task=set_base_maps.validate()
            .handle_errors(task_instance_id="configure_base_maps")
            .set_executor("lithops"),
            partial=(params_dict.get("configure_base_maps") or {}),
            method="call",
        ),
        "subject_observations": Node(
            async_task=get_subjectgroup_observations.validate()
            .handle_errors(task_instance_id="subject_observations")
            .set_executor("lithops"),
            partial={
                "client": DependsOn("er_client_name"),
                "time_range": DependsOn("time_range"),
                "raise_on_empty": False,
                "include_details": False,
                "include_subjectsource_details": False,
            }
            | (params_dict.get("subject_observations") or {}),
            method="call",
        ),
        "extract_precipitation": Node(
            async_task=extract_value_from_json_column.validate()
            .handle_errors(task_instance_id="extract_precipitation")
            .set_executor("lithops"),
            partial={
                "df": DependsOn("subject_observations"),
                "column_name": "extra__observation_details",
                "field_name_options": ["precipitation"],
                "output_type": "float",
                "output_column_name": "precipitation",
            }
            | (params_dict.get("extract_precipitation") or {}),
            method="call",
        ),
        "extract_temperature": Node(
            async_task=extract_value_from_json_column.validate()
            .handle_errors(task_instance_id="extract_temperature")
            .set_executor("lithops"),
            partial={
                "df": DependsOn("extract_precipitation"),
                "column_name": "extra__observation_details",
                "field_name_options": ["surface_air_temperature"],
                "output_type": "float",
                "output_column_name": "temperature",
            }
            | (params_dict.get("extract_temperature") or {}),
            method="call",
        ),
        "extract_date": Node(
            async_task=extract_column_as_type.validate()
            .handle_errors(task_instance_id="extract_date")
            .set_executor("lithops"),
            partial={
                "df": DependsOn("extract_temperature"),
                "column_name": "fixtime",
                "output_type": "date",
                "output_column_name": "date",
            }
            | (params_dict.get("extract_date") or {}),
            method="call",
        ),
        "rename_grouper_columns": Node(
            async_task=map_columns.validate()
            .handle_errors(task_instance_id="rename_grouper_columns")
            .set_executor("lithops"),
            partial={
                "df": DependsOn("extract_date"),
                "drop_columns": [],
                "retain_columns": [],
                "rename_columns": {"extra__subject__name": "weather_station"},
            }
            | (params_dict.get("rename_grouper_columns") or {}),
            method="call",
        ),
        "df_with_temporal_index": Node(
            async_task=add_temporal_index.validate()
            .handle_errors(task_instance_id="df_with_temporal_index")
            .set_executor("lithops"),
            partial={
                "df": DependsOn("rename_grouper_columns"),
                "time_col": "fixtime",
                "groupers": DependsOn("groupers"),
            }
            | (params_dict.get("df_with_temporal_index") or {}),
            method="call",
        ),
        "split_weather_groups": Node(
            async_task=split_groups.validate()
            .handle_errors(task_instance_id="split_weather_groups")
            .set_executor("lithops"),
            partial={
                "df": DependsOn("df_with_temporal_index"),
                "groupers": DependsOn("groupers"),
            }
            | (params_dict.get("split_weather_groups") or {}),
            method="call",
        ),
        "daily_weather": Node(
            async_task=summarize_df.validate()
            .handle_errors(task_instance_id="daily_weather")
            .set_executor("lithops"),
            partial={
                "groupby_cols": ["weather_station", "date"],
                "summary_params": [
                    {
                        "display_name": "daily_precipitation",
                        "aggregator": "sum",
                        "column": "precipitation",
                    },
                    {
                        "display_name": "daily_temperature",
                        "aggregator": "mean",
                        "column": "temperature",
                    },
                ],
                "reset_index": True,
            }
            | (params_dict.get("daily_weather") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("split_weather_groups"),
            },
        ),
        "precipitation_chart": Node(
            async_task=draw_line_chart.validate()
            .handle_errors(task_instance_id="precipitation_chart")
            .set_executor("lithops"),
            partial={
                "x_column": "date",
                "y_column": "daily_precipitation",
                "category_column": "weather_station",
                "line_kwargs": {"shape": "linear"},
                "layout_kwargs": {
                    "title": "Precipitation by Station",
                    "title_x": 0.01,
                    "title_y": 0.95,
                    "showlegend": True,
                    "fontsize": 12,
                    "fontcolor": "#222222",
                    "xaxis": {
                        "title": "Date",
                        "tickformat": "%Y-%m-%d",
                        "tickangle": -45,
                        "rangemode": "auto",
                    },
                    "yaxis": {"title": "Precipitation (mm)", "tickformat": ".1f"},
                    "legend_title": "Weather Station",
                    "hovermode": "x unified",
                },
            }
            | (params_dict.get("precipitation_chart") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["dataframe"],
                "argvalues": DependsOn("daily_weather"),
            },
        ),
        "persist_precipitation": Node(
            async_task=persist_text.validate()
            .handle_errors(task_instance_id="persist_precipitation")
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            }
            | (params_dict.get("persist_precipitation") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["text"],
                "argvalues": DependsOn("precipitation_chart"),
            },
        ),
        "precipitation_chart_widget": Node(
            async_task=create_plot_widget_single_view.validate()
            .handle_errors(task_instance_id="precipitation_chart_widget")
            .set_executor("lithops"),
            partial={
                "title": "Daily Precipitation by Station",
            }
            | (params_dict.get("precipitation_chart_widget") or {}),
            method="map",
            kwargs={
                "argnames": ["view", "data"],
                "argvalues": DependsOn("persist_precipitation"),
            },
        ),
        "grouped_precipitation_widget": Node(
            async_task=merge_widget_views.validate()
            .handle_errors(task_instance_id="grouped_precipitation_widget")
            .set_executor("lithops"),
            partial={
                "widgets": DependsOn("precipitation_chart_widget"),
            }
            | (params_dict.get("grouped_precipitation_widget") or {}),
            method="call",
        ),
        "temperature_chart": Node(
            async_task=draw_line_chart.validate()
            .handle_errors(task_instance_id="temperature_chart")
            .set_executor("lithops"),
            partial={
                "x_column": "date",
                "y_column": "daily_temperature",
                "category_column": "weather_station",
                "line_kwargs": {"shape": "linear"},
                "layout_kwargs": {
                    "title": "Temperature by Station",
                    "title_x": 0.01,
                    "title_y": 0.95,
                    "showlegend": True,
                    "fontsize": 12,
                    "fontcolor": "#222222",
                    "xaxis": {
                        "title": "Date",
                        "tickformat": "%Y-%m-%d",
                        "tickangle": -45,
                        "rangemode": "auto",
                    },
                    "yaxis": {"title": "Average Temperature (°C)", "tickformat": ".1f"},
                    "legend_title": "Weather Station",
                    "hovermode": "x unified",
                },
            }
            | (params_dict.get("temperature_chart") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["dataframe"],
                "argvalues": DependsOn("daily_weather"),
            },
        ),
        "persist_temperature": Node(
            async_task=persist_text.validate()
            .handle_errors(task_instance_id="persist_temperature")
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            }
            | (params_dict.get("persist_temperature") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["text"],
                "argvalues": DependsOn("temperature_chart"),
            },
        ),
        "temperature_chart_widget": Node(
            async_task=create_plot_widget_single_view.validate()
            .handle_errors(task_instance_id="temperature_chart_widget")
            .set_executor("lithops"),
            partial={
                "title": "Daily Temperature by Station",
            }
            | (params_dict.get("temperature_chart_widget") or {}),
            method="map",
            kwargs={
                "argnames": ["view", "data"],
                "argvalues": DependsOn("persist_temperature"),
            },
        ),
        "grouped_temperature_widget": Node(
            async_task=merge_widget_views.validate()
            .handle_errors(task_instance_id="grouped_temperature_widget")
            .set_executor("lithops"),
            partial={
                "widgets": DependsOn("temperature_chart_widget"),
            }
            | (params_dict.get("grouped_temperature_widget") or {}),
            method="call",
        ),
        "get_events_data": Node(
            async_task=get_events.validate()
            .handle_errors(task_instance_id="get_events_data")
            .set_executor("lithops"),
            partial={
                "client": DependsOn("er_client_name"),
                "time_range": DependsOn("time_range"),
                "event_columns": [
                    "id",
                    "time",
                    "event_type",
                    "event_category",
                    "reported_by",
                    "serial_number",
                    "geometry",
                    "created_at",
                    "event_details",
                ],
                "raise_on_empty": False,
                "include_details": True,
                "include_updates": False,
                "include_related_events": False,
            }
            | (params_dict.get("get_events_data") or {}),
            method="call",
        ),
        "extract_event_date": Node(
            async_task=extract_column_as_type.validate()
            .handle_errors(task_instance_id="extract_event_date")
            .set_executor("lithops"),
            partial={
                "df": DependsOn("get_events_data"),
                "column_name": "created_at",
                "output_type": "date",
                "output_column_name": "date",
            }
            | (params_dict.get("extract_event_date") or {}),
            method="call",
        ),
        "events_wtemporal": Node(
            async_task=add_temporal_index.validate()
            .handle_errors(task_instance_id="events_wtemporal")
            .set_executor("lithops"),
            partial={
                "df": DependsOn("extract_event_date"),
                "time_col": "created_at",
                "groupers": DependsOn("groupers"),
            }
            | (params_dict.get("events_wtemporal") or {}),
            method="call",
        ),
        "split_event_groups": Node(
            async_task=split_groups.validate()
            .handle_errors(task_instance_id="split_event_groups")
            .set_executor("lithops"),
            partial={
                "df": DependsOn("events_wtemporal"),
                "groupers": DependsOn("groupers"),
            }
            | (params_dict.get("split_event_groups") or {}),
            method="call",
        ),
        "total_events_recorded": Node(
            async_task=summarize_df.validate()
            .handle_errors(task_instance_id="total_events_recorded")
            .set_executor("lithops"),
            partial={
                "groupby_cols": ["date"],
                "summary_params": [
                    {
                        "display_name": "no_of_events",
                        "aggregator": "nunique",
                        "column": "id",
                    }
                ],
                "reset_index": True,
            }
            | (params_dict.get("total_events_recorded") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("split_event_groups"),
            },
        ),
        "persist_tevents_df": Node(
            async_task=persist_df.validate()
            .handle_errors(task_instance_id="persist_tevents_df")
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            }
            | (params_dict.get("persist_tevents_df") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("total_events_recorded"),
            },
        ),
        "draw_events_chart": Node(
            async_task=draw_line_chart.validate()
            .handle_errors(task_instance_id="draw_events_chart")
            .set_executor("lithops"),
            partial={
                "x_column": "date",
                "y_column": "no_of_events",
                "line_kwargs": {"shape": "linear"},
                "layout_kwargs": {
                    "title": "Total events recorded",
                    "title_x": 0.01,
                    "title_y": 0.95,
                    "showlegend": False,
                    "fontsize": 12,
                    "fontcolor": "#222222",
                    "xaxis": {
                        "title": "Date",
                        "tickformat": "%Y-%m-%d",
                        "tickangle": -45,
                        "rangemode": "auto",
                    },
                    "yaxis": {"title": "Count", "tickformat": ".1f"},
                    "hovermode": "x unified",
                },
            }
            | (params_dict.get("draw_events_chart") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["dataframe"],
                "argvalues": DependsOn("total_events_recorded"),
            },
        ),
        "persist_total_events": Node(
            async_task=persist_text.validate()
            .handle_errors(task_instance_id="persist_total_events")
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            }
            | (params_dict.get("persist_total_events") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["text"],
                "argvalues": DependsOn("draw_events_chart"),
            },
        ),
        "tevents_chart_widget": Node(
            async_task=create_plot_widget_single_view.validate()
            .handle_errors(task_instance_id="tevents_chart_widget")
            .set_executor("lithops"),
            partial={
                "title": "Total Events",
            }
            | (params_dict.get("tevents_chart_widget") or {}),
            method="map",
            kwargs={
                "argnames": ["view", "data"],
                "argvalues": DependsOn("persist_total_events"),
            },
        ),
        "grouped_tevents_widget": Node(
            async_task=merge_widget_views.validate()
            .handle_errors(task_instance_id="grouped_tevents_widget")
            .set_executor("lithops"),
            partial={
                "widgets": DependsOn("tevents_chart_widget"),
            }
            | (params_dict.get("grouped_tevents_widget") or {}),
            method="call",
        ),
        "filter_patrol_info_events": Node(
            async_task=filter_by_value.validate()
            .handle_errors(task_instance_id="filter_patrol_info_events")
            .set_executor("lithops"),
            partial={
                "column_name": "event_type",
                "value": "patrol_information",
            }
            | (params_dict.get("filter_patrol_info_events") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("split_event_groups"),
            },
        ),
        "normalize_pi_values": Node(
            async_task=normalize_column.validate()
            .handle_errors(task_instance_id="normalize_pi_values")
            .set_executor("lithops"),
            partial={
                "column": "event_details",
            }
            | (params_dict.get("normalize_pi_values") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("filter_patrol_info_events"),
            },
        ),
        "rename_patrolinf_cols": Node(
            async_task=map_columns.validate()
            .handle_errors(task_instance_id="rename_patrolinf_cols")
            .set_executor("lithops"),
            partial={
                "drop_columns": [],
                "retain_columns": [],
                "rename_columns": {
                    "event_details__participants": "participants",
                    "event_details__patrol_purpose": "purpose",
                    "event_details__person_who_authorized": "authorized_by",
                },
                "df": DependsOn("normalize_pi_values"),
            }
            | (params_dict.get("rename_patrolinf_cols") or {}),
            method="call",
        ),
        "patrol_info_summary": Node(
            async_task=summarize_df.validate()
            .handle_errors(task_instance_id="patrol_info_summary")
            .set_executor("lithops"),
            partial={
                "groupby_cols": ["purpose"],
                "summary_params": [
                    {
                        "display_name": "Number of Patrols",
                        "aggregator": "count",
                        "column": "id",
                    }
                ],
                "reset_index": True,
            }
            | (params_dict.get("patrol_info_summary") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("rename_patrolinf_cols"),
            },
        ),
        "include_pat_totals": Node(
            async_task=add_totals_row.validate()
            .handle_errors(task_instance_id="include_pat_totals")
            .set_executor("lithops"),
            partial={
                "label_col": ["purpose"],
            }
            | (params_dict.get("include_pat_totals") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("patrol_info_summary"),
            },
        ),
        "persist_patrol_df": Node(
            async_task=persist_df.validate()
            .handle_errors(task_instance_id="persist_patrol_df")
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            }
            | (params_dict.get("persist_patrol_df") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("include_pat_totals"),
            },
        ),
        "patrol_observations": Node(
            async_task=get_patrol_observations.validate()
            .handle_errors(task_instance_id="patrol_observations")
            .set_executor("lithops"),
            partial={
                "client": DependsOn("er_client_name"),
                "time_range": DependsOn("time_range"),
                "include_patrol_details": True,
                "raise_on_empty": True,
            }
            | (params_dict.get("patrol_observations") or {}),
            method="call",
        ),
        "patrol_relocs": Node(
            async_task=process_relocations.validate()
            .handle_errors(task_instance_id="patrol_relocs")
            .set_executor("lithops"),
            partial={
                "observations": DependsOn("patrol_observations"),
                "relocs_columns": [
                    "extra__id",
                    "extra__created_at",
                    "extra__subject_id",
                    "geometry",
                    "groupby_col",
                    "fixtime",
                    "junk_status",
                    "patrol_id",
                    "patrol_title",
                    "patrol_serial_number",
                    "patrol_start_time",
                    "patrol_end_time",
                    "patrol_type",
                    "patrol_status",
                    "patrol_subject",
                    "patrol_type__value",
                ],
                "filter_point_coords": [
                    {"x": 180.0, "y": 90.0},
                    {"x": 0.0, "y": 0.0},
                    {"x": 1.0, "y": 1.0},
                ],
            }
            | (params_dict.get("patrol_relocs") or {}),
            method="call",
        ),
        "convert_to_trajectories": Node(
            async_task=relocations_to_trajectory.validate()
            .handle_errors(task_instance_id="convert_to_trajectories")
            .set_executor("lithops"),
            partial={
                "relocations": DependsOn("patrol_relocs"),
            }
            | (params_dict.get("convert_to_trajectories") or {}),
            method="call",
        ),
        "add_temporal_index_to_traj": Node(
            async_task=add_temporal_index.validate()
            .handle_errors(task_instance_id="add_temporal_index_to_traj")
            .set_executor("lithops"),
            partial={
                "df": DependsOn("convert_to_trajectories"),
                "time_col": "segment_start",
                "groupers": DependsOn("groupers"),
                "cast_to_datetime": True,
                "format": "mixed",
            }
            | (params_dict.get("add_temporal_index_to_traj") or {}),
            method="call",
        ),
        "map_patrol_types": Node(
            async_task=classify_mnc_patrol.validate()
            .handle_errors(task_instance_id="map_patrol_types")
            .set_executor("lithops"),
            partial={
                "df": DependsOn("add_temporal_index_to_traj"),
                "patrol_col": "extra__patrol_type__value",
                "new_col": "patrol_cat_types",
            }
            | (params_dict.get("map_patrol_types") or {}),
            method="call",
        ),
        "rename_traj_cols": Node(
            async_task=map_columns.validate()
            .handle_errors(task_instance_id="rename_traj_cols")
            .set_executor("lithops"),
            partial={
                "drop_columns": ["heading", "extra__created_at", "extra__id"],
                "retain_columns": [],
                "rename_columns": {
                    "extra__patrol_start_time": "patrol_start_time",
                    "extra__patrol_end_time": "patrol_end_time",
                    "extra__patrol_id": "patrol_id",
                    "extra__patrol_serial_number": "patrol_serial_number",
                    "extra__patrol_status": "patrol_status",
                    "extra__patrol_subject": "patrol_subject_name",
                    "extra__patrol_title": "patrol_title",
                    "extra__patrol_type": "patrol_type_id",
                    "extra__patrol_type__value": "patrol_type_value",
                    "extra__subject_id": "subject_id",
                },
                "df": DependsOn("map_patrol_types"),
            }
            | (params_dict.get("rename_traj_cols") or {}),
            method="call",
        ),
        "split_trajectories_by_group": Node(
            async_task=split_groups.validate()
            .handle_errors(task_instance_id="split_trajectories_by_group")
            .set_executor("lithops"),
            partial={
                "df": DependsOn("rename_traj_cols"),
                "groupers": DependsOn("groupers"),
            }
            | (params_dict.get("split_trajectories_by_group") or {}),
            method="call",
        ),
        "filter_foot_patrols": Node(
            async_task=filter_by_value.validate()
            .handle_errors(task_instance_id="filter_foot_patrols")
            .set_executor("lithops"),
            partial={
                "column_name": "patrol_cat_types",
                "value": "Foot",
            }
            | (params_dict.get("filter_foot_patrols") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("split_trajectories_by_group"),
            },
        ),
        "apply_footp_colormap": Node(
            async_task=apply_color_map.validate()
            .handle_errors(task_instance_id="apply_footp_colormap")
            .set_executor("lithops"),
            partial={
                "input_column_name": "patrol_type_value",
                "output_column_name": "patrol_colormap",
                "colormap": "coolwarm",
            }
            | (params_dict.get("apply_footp_colormap") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("filter_foot_patrols"),
            },
        ),
        "generate_footp_layers": Node(
            async_task=create_polyline_layer.validate()
            .handle_errors(task_instance_id="generate_footp_layers")
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "layer_style": {"color_column": "patrol_colormap"},
                "legend": {
                    "label_column": "patrol_type_value",
                    "color_column": "patrol_colormap",
                },
                "tooltip_columns": [
                    "patrol_subject_name",
                    "patrol_start_time",
                    "patrol_end_time",
                    "patrol_title",
                    "patrol_type_value",
                    "segment_start",
                    "dist_meters",
                    "timespan_seconds",
                ],
            }
            | (params_dict.get("generate_footp_layers") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["geodataframe"],
                "argvalues": DependsOn("apply_footp_colormap"),
            },
        ),
        "zoom_footp_traj_view": Node(
            async_task=create_view_state_from_gdf.validate()
            .handle_errors(task_instance_id="zoom_footp_traj_view")
            .set_executor("lithops"),
            partial={
                "pitch": 0,
                "bearing": 0,
            }
            | (params_dict.get("zoom_footp_traj_view") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["gdf"],
                "argvalues": DependsOn("apply_footp_colormap"),
            },
        ),
        "zip_footp_zoom_values": Node(
            async_task=zip_grouped_by_key.validate()
            .handle_errors(task_instance_id="zip_footp_zoom_values")
            .set_executor("lithops"),
            partial={
                "left": DependsOn("generate_footp_layers"),
                "right": DependsOn("zoom_footp_traj_view"),
            }
            | (params_dict.get("zip_footp_zoom_values") or {}),
            method="call",
        ),
        "draw_footp_ecomap": Node(
            async_task=draw_ecomap.validate()
            .handle_errors(task_instance_id="draw_footp_ecomap")
            .set_executor("lithops"),
            partial={
                "tile_layers": DependsOn("configure_base_maps"),
                "north_arrow_style": {"placement": "top-left"},
                "legend_style": {"placement": "bottom-right", "title": "Patrol Types"},
                "static": False,
                "title": None,
                "max_zoom": 20,
            }
            | (params_dict.get("draw_footp_ecomap") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["geo_layers", "view_state"],
                "argvalues": DependsOn("zip_footp_zoom_values"),
            },
        ),
        "persist_footp_ecomap_urls": Node(
            async_task=persist_text.validate()
            .handle_errors(task_instance_id="persist_footp_ecomap_urls")
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            }
            | (params_dict.get("persist_footp_ecomap_urls") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["text"],
                "argvalues": DependsOn("draw_footp_ecomap"),
            },
        ),
        "create_footp_widgets": Node(
            async_task=create_map_widget_single_view.validate()
            .handle_errors(task_instance_id="create_footp_widgets")
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": "Foot Patrol",
            }
            | (params_dict.get("create_footp_widgets") or {}),
            method="map",
            kwargs={
                "argnames": ["view", "data"],
                "argvalues": DependsOn("persist_footp_ecomap_urls"),
            },
        ),
        "merge_footp_widgets": Node(
            async_task=merge_widget_views.validate()
            .handle_errors(task_instance_id="merge_footp_widgets")
            .set_executor("lithops"),
            partial={
                "widgets": DependsOn("create_footp_widgets"),
            }
            | (params_dict.get("merge_footp_widgets") or {}),
            method="call",
        ),
        "filter_vehicle_patrols": Node(
            async_task=filter_by_value.validate()
            .handle_errors(task_instance_id="filter_vehicle_patrols")
            .set_executor("lithops"),
            partial={
                "column_name": "patrol_cat_types",
                "value": "Vehicle",
            }
            | (params_dict.get("filter_vehicle_patrols") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("split_trajectories_by_group"),
            },
        ),
        "apply_vhp_colormap": Node(
            async_task=apply_color_map.validate()
            .handle_errors(task_instance_id="apply_vhp_colormap")
            .set_executor("lithops"),
            partial={
                "input_column_name": "patrol_type_value",
                "output_column_name": "patrol_colormap",
                "colormap": "coolwarm",
            }
            | (params_dict.get("apply_vhp_colormap") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("filter_vehicle_patrols"),
            },
        ),
        "generate_vhp_layers": Node(
            async_task=create_polyline_layer.validate()
            .handle_errors(task_instance_id="generate_vhp_layers")
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "layer_style": {"color_column": "patrol_colormap"},
                "legend": {
                    "label_column": "patrol_type_value",
                    "color_column": "patrol_colormap",
                },
                "tooltip_columns": [
                    "patrol_subject_name",
                    "patrol_start_time",
                    "patrol_end_time",
                    "patrol_title",
                    "patrol_type_value",
                    "segment_start",
                    "dist_meters",
                    "timespan_seconds",
                ],
            }
            | (params_dict.get("generate_vhp_layers") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["geodataframe"],
                "argvalues": DependsOn("apply_vhp_colormap"),
            },
        ),
        "zoom_vhp_traj_view": Node(
            async_task=create_view_state_from_gdf.validate()
            .handle_errors(task_instance_id="zoom_vhp_traj_view")
            .set_executor("lithops"),
            partial={
                "pitch": 0,
                "bearing": 0,
            }
            | (params_dict.get("zoom_vhp_traj_view") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["gdf"],
                "argvalues": DependsOn("apply_vhp_colormap"),
            },
        ),
        "zip_vhp_zoom_values": Node(
            async_task=zip_grouped_by_key.validate()
            .handle_errors(task_instance_id="zip_vhp_zoom_values")
            .set_executor("lithops"),
            partial={
                "left": DependsOn("generate_vhp_layers"),
                "right": DependsOn("zoom_vhp_traj_view"),
            }
            | (params_dict.get("zip_vhp_zoom_values") or {}),
            method="call",
        ),
        "draw_vhp_ecomap": Node(
            async_task=draw_ecomap.validate()
            .handle_errors(task_instance_id="draw_vhp_ecomap")
            .set_executor("lithops"),
            partial={
                "tile_layers": DependsOn("configure_base_maps"),
                "north_arrow_style": {"placement": "top-left"},
                "legend_style": {"placement": "bottom-right", "title": "Patrol Types"},
                "static": False,
                "title": None,
                "max_zoom": 20,
            }
            | (params_dict.get("draw_vhp_ecomap") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["geo_layers", "view_state"],
                "argvalues": DependsOn("zip_vhp_zoom_values"),
            },
        ),
        "persist_vhp_ecomap_urls": Node(
            async_task=persist_text.validate()
            .handle_errors(task_instance_id="persist_vhp_ecomap_urls")
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            }
            | (params_dict.get("persist_vhp_ecomap_urls") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["text"],
                "argvalues": DependsOn("draw_vhp_ecomap"),
            },
        ),
        "create_vhp_widgets": Node(
            async_task=create_map_widget_single_view.validate()
            .handle_errors(task_instance_id="create_vhp_widgets")
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": "Vehicle Patrol",
            }
            | (params_dict.get("create_vhp_widgets") or {}),
            method="map",
            kwargs={
                "argnames": ["view", "data"],
                "argvalues": DependsOn("persist_vhp_ecomap_urls"),
            },
        ),
        "merge_vhp_widgets": Node(
            async_task=merge_widget_views.validate()
            .handle_errors(task_instance_id="merge_vhp_widgets")
            .set_executor("lithops"),
            partial={
                "widgets": DependsOn("create_vhp_widgets"),
            }
            | (params_dict.get("merge_vhp_widgets") or {}),
            method="call",
        ),
        "filter_motor_patrols": Node(
            async_task=filter_by_value.validate()
            .handle_errors(task_instance_id="filter_motor_patrols")
            .set_executor("lithops"),
            partial={
                "column_name": "patrol_cat_types",
                "value": "Motorcycle",
            }
            | (params_dict.get("filter_motor_patrols") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("split_trajectories_by_group"),
            },
        ),
        "apply_mocp_colormap": Node(
            async_task=apply_color_map.validate()
            .handle_errors(task_instance_id="apply_mocp_colormap")
            .set_executor("lithops"),
            partial={
                "input_column_name": "patrol_type_value",
                "output_column_name": "patrol_colormap",
                "colormap": "coolwarm",
            }
            | (params_dict.get("apply_mocp_colormap") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("filter_motor_patrols"),
            },
        ),
        "generate_mocp_layers": Node(
            async_task=create_polyline_layer.validate()
            .handle_errors(task_instance_id="generate_mocp_layers")
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "layer_style": {"color_column": "patrol_colormap"},
                "legend": {
                    "label_column": "patrol_type_value",
                    "color_column": "patrol_colormap",
                },
                "tooltip_columns": [
                    "patrol_subject_name",
                    "patrol_start_time",
                    "patrol_end_time",
                    "patrol_title",
                    "patrol_type_value",
                    "segment_start",
                    "dist_meters",
                    "timespan_seconds",
                ],
            }
            | (params_dict.get("generate_mocp_layers") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["geodataframe"],
                "argvalues": DependsOn("apply_mocp_colormap"),
            },
        ),
        "zoom_mocp_traj_view": Node(
            async_task=create_view_state_from_gdf.validate()
            .handle_errors(task_instance_id="zoom_mocp_traj_view")
            .set_executor("lithops"),
            partial={
                "pitch": 0,
                "bearing": 0,
            }
            | (params_dict.get("zoom_mocp_traj_view") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["gdf"],
                "argvalues": DependsOn("apply_mocp_colormap"),
            },
        ),
        "zip_mocp_zoom_values": Node(
            async_task=zip_grouped_by_key.validate()
            .handle_errors(task_instance_id="zip_mocp_zoom_values")
            .set_executor("lithops"),
            partial={
                "left": DependsOn("generate_mocp_layers"),
                "right": DependsOn("zoom_mocp_traj_view"),
            }
            | (params_dict.get("zip_mocp_zoom_values") or {}),
            method="call",
        ),
        "draw_mocp_ecomap": Node(
            async_task=draw_ecomap.validate()
            .handle_errors(task_instance_id="draw_mocp_ecomap")
            .set_executor("lithops"),
            partial={
                "tile_layers": DependsOn("configure_base_maps"),
                "north_arrow_style": {"placement": "top-left"},
                "legend_style": {"placement": "bottom-right", "title": "Patrol Types"},
                "static": False,
                "title": None,
                "max_zoom": 20,
            }
            | (params_dict.get("draw_mocp_ecomap") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["geo_layers", "view_state"],
                "argvalues": DependsOn("zip_mocp_zoom_values"),
            },
        ),
        "persist_mocp_ecomap_urls": Node(
            async_task=persist_text.validate()
            .handle_errors(task_instance_id="persist_mocp_ecomap_urls")
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            }
            | (params_dict.get("persist_mocp_ecomap_urls") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["text"],
                "argvalues": DependsOn("draw_mocp_ecomap"),
            },
        ),
        "create_mocp_widgets": Node(
            async_task=create_map_widget_single_view.validate()
            .handle_errors(task_instance_id="create_mocp_widgets")
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": "Motorbike Patrol",
            }
            | (params_dict.get("create_mocp_widgets") or {}),
            method="map",
            kwargs={
                "argnames": ["view", "data"],
                "argvalues": DependsOn("persist_mocp_ecomap_urls"),
            },
        ),
        "merge_mocp_widgets": Node(
            async_task=merge_widget_views.validate()
            .handle_errors(task_instance_id="merge_mocp_widgets")
            .set_executor("lithops"),
            partial={
                "widgets": DependsOn("create_mocp_widgets"),
            }
            | (params_dict.get("merge_mocp_widgets") or {}),
            method="call",
        ),
        "patrol_grid_visits": Node(
            async_task=create_patrol_coverage_grid.validate()
            .handle_errors(task_instance_id="patrol_grid_visits")
            .set_executor("lithops"),
            partial={
                "grid_cell_size": 1000,
            }
            | (params_dict.get("patrol_grid_visits") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["trajs"],
                "argvalues": DependsOn("split_trajectories_by_group"),
            },
        ),
        "apply_classification_grid": Node(
            async_task=apply_classification.validate()
            .handle_errors(task_instance_id="apply_classification_grid")
            .set_executor("lithops"),
            partial={
                "input_column_name": "unique_patrol_count",
                "output_column_name": "density_bins",
            }
            | (params_dict.get("apply_classification_grid") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("patrol_grid_visits"),
            },
        ),
        "apply_grid_colormap": Node(
            async_task=apply_color_map.validate()
            .handle_errors(task_instance_id="apply_grid_colormap")
            .set_executor("lithops"),
            partial={
                "input_column_name": "density_bins",
                "output_column_name": "density_colormap",
                "colormap": "Wistia",
            }
            | (params_dict.get("apply_grid_colormap") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("apply_classification_grid"),
            },
        ),
        "ranger_patrol_metrics": Node(
            async_task=summarize_df.validate()
            .handle_errors(task_instance_id="ranger_patrol_metrics")
            .set_executor("lithops"),
            partial={
                "groupby_cols": ["patrol_subject_name"],
                "summary_params": [
                    {
                        "display_name": "Number of Patrols",
                        "aggregator": "nunique",
                        "column": "patrol_id",
                    },
                    {
                        "display_name": "Distance (km)",
                        "aggregator": "sum",
                        "column": "dist_meters",
                        "original_unit": "METER",
                        "new_unit": "KILOMETER",
                    },
                    {
                        "display_name": "Duration (hrs)",
                        "aggregator": "sum",
                        "column": "timespan_seconds",
                        "original_unit": "SECOND",
                        "new_unit": "HOUR",
                    },
                ],
                "reset_index": True,
            }
            | (params_dict.get("ranger_patrol_metrics") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("split_trajectories_by_group"),
            },
        ),
        "persist_total_df": Node(
            async_task=persist_df.validate()
            .handle_errors(task_instance_id="persist_total_df")
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            }
            | (params_dict.get("persist_total_df") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("ranger_patrol_metrics"),
            },
        ),
        "weather_dashboard": Node(
            async_task=gather_dashboard.validate()
            .handle_errors(task_instance_id="weather_dashboard")
            .set_executor("lithops"),
            partial={
                "details": DependsOn("workflow_details"),
                "widgets": DependsOnSequence(
                    [
                        DependsOn("grouped_precipitation_widget"),
                        DependsOn("grouped_temperature_widget"),
                        DependsOn("grouped_tevents_widget"),
                        DependsOn("merge_footp_widgets"),
                        DependsOn("merge_vhp_widgets"),
                        DependsOn("merge_mocp_widgets"),
                    ],
                ),
                "time_range": DependsOn("time_range"),
                "groupers": DependsOn("groupers"),
            }
            | (params_dict.get("weather_dashboard") or {}),
            method="call",
        ),
    }
    graph = Graph(dependencies=dependencies, nodes=nodes)
    results = graph.execute()
    return results
